# -*- coding: utf-8 -*-
"""GTHL-Emo_Proposed_Model_Semeval-2018.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuwZhWk1gegfeuR6JaB5nqY6CJ-igD4l
"""

!pip install emoji
import warnings
warnings.filterwarnings("ignore", message="`encoder_attention_mask` is deprecated", category=FutureWarning)
import emoji

import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from transformers import AutoTokenizer, AutoModel
import re
from tqdm import tqdm
import logging
from sklearn.metrics import jaccard_score, f1_score, precision_score, recall_score, confusion_matrix, average_precision_score, hamming_loss
import json
from torch.amp import GradScaler, autocast
from scipy import sparse
from scipy.stats import entropy
import shutil
import urllib3
import emoji
import time

# Disable urllib3 warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

CONFIG = {
    'seed': 42,
    'max_length': 128,
    'batch_size': 8, # Increased batch size from 2 to 8
    'epochs': 7,
    'learning_rate': 1e-5,
    'weight_decay': 0.02,
    'patience': 7,
    'dropout_rate': 0.3, # Added dropout rate
    'data_paths': {
        'train': './Train.xlsx',
        'dev': './Validation.xlsx',
        'test': './Test.xlsx',
    },
    'results_dir': './result_final/',
    'emotion_labels': ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
    'embedding_dim': 768,
    'focal_lambda': 0.1,
    'graph_lambda': 0.1,
    'ranking_lambda': 0.1,
    'temperature': 0.07,
    'mc_dropout_samples': 5,
    'gcn_hidden_dim': 768,
    'similarity_threshold': 0.5,
    'min_lambda': 0.05,
    'ema_alpha': 0.95,
    'gcn_layers': 1,
    'top_k_spans': 5,
    'lambda1': 0.5,
    'lambda2': 0.5,
    'graphsage_neighbors': 5,
    'label_transformer_layers': 2,
    'label_transformer_heads': 8,
    'verbose_logging': True,
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    'min_valid_tokens': 3
}

# Emoji mapping for preprocessing
emoji_map = {
    '😠': 'غاضب', '😡': 'غاضب', '🤬': 'غاضب', '💢': 'غاضب', '😤': 'غاضب', '😾': 'غاضب', '💪': 'غاضب',
    '🤔': 'مترقب', '👀': 'مترقب', '🕐': 'مترقب', '⏳': 'مترقب', '🎯': 'مترقب', '🔍': 'مترقب',
    '🤢': 'مقرف', '🤮': 'مقرف', '🤧': 'مقرف', '😫': 'مقرف', '🥴': 'مقرف',
    '😨': 'خائف', '😱': 'خائف', '😰': 'خائف', '😥': 'خائف', '🥶': 'خائف', '😖': 'خائف',
    '😊': 'سعيد', '😃': 'سعيد', '😄': 'سعيد', '😁': 'سعيد', '🤗': 'سعيد', '😂': 'سعيد', '🤣': 'سعيد',
    '😅': 'سعيد', '😆': 'سعيد', '🎉': 'سعيد', '✨': 'سعيد',
    '❤️': 'محب', '💕': 'محب', '💗': 'محب', '💖': 'محب', '🥰': 'محب', '😍': 'محب', '😘': 'محب',
    '💝': 'محب', '💑': 'محب',
    '🌟': 'تفاؤل', '🌞': 'تفاؤل', '⭐': 'تفاؤل', '🎊': 'تفاؤل', '🌈': 'تفاؤل', '💫': 'تفاؤل', '🙏': 'تفاؤل',
    '😔': 'حزين', '😕': 'حزين', '😩': 'حزين', '🥺': 'حزين', '😣': 'حزين', '😟': 'حزين', '🤦': 'حزين', '👎': 'حزين',
    '😢': 'حزين', '😭': 'حزين', '😥': 'حزين', '💔': 'حزين', '😪': 'حزين', '🥀': 'حزين', '😿': 'حزين', '😴': 'حزين', '🎭': 'حزين',
    '😮': 'مندهش', '😯': 'مندهش', '😲': 'مندهش', '😳': 'مندهش', '🤯': 'مندهش', '😱': 'مندهش',
    '😐': 'ثقة', '😑': 'ثقة', '😶': 'ثقة', '🙂': 'ثقة', '😬': 'ثقة'
}

# Logging and directory setup
os.makedirs(CONFIG['results_dir'], exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(CONFIG['results_dir'], 'pipeline.log')),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger()

# Set random seed
def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_random_seed(CONFIG['seed'])
device = torch.device(CONFIG['device'])
device_type = CONFIG['device']

# Disk space management
def check_disk_space(path):
    stat = shutil.disk_usage(path)
    free_space = stat.free / (1024 ** 3)  # Free space in GB
    logger.info(f"Free disk space in {path}: {free_space:.2f} GB")
    print(f"Free disk space in {path}: {free_space:.2f} GB")
    return free_space > 1

def cleanup_old_models(directory):
    for file in os.listdir(directory):
        if file.endswith('.pth'):
            try:
                os.remove(os.path.join(directory, file))
                logger.info(f"Removed old model file: {file}")
                print(f"Removed old model file: {file}")
            except Exception as e:
                logger.warning(f"Failed to remove {file}: {e}")
                print(f"Failed to remove {file}: {e}")

# ===============================
# PART 2: Data Preprocessing and Loading
# ===============================

def compute_text_complexity(text):
    tokens = tokenize_text(text)
    unique_tokens = len(set(tokens))
    avg_token_length = np.mean([len(t) for t in tokens]) if tokens else 1.0
    return unique_tokens / len(tokens) if tokens else 0.0, avg_token_length

def tokenize_text(text, complexity=0.5):
    if complexity > 0.7:
        tokens = re.findall(r'\w+|[^\w\s]', text, re.UNICODE)
    else:
        tokens = text.split()
    return tokens

def preprocess_text(text, complexity=None):
    if not isinstance(text, str) or not text.strip():
        return "[EMPTY]"
    for emoji_char, emotion_word in emoji_map.items():
        text = text.replace(emoji_char, f" {emotion_word} ")
    text = emoji.demojize(text, language='ar')
    text = re.sub(r'http\S+|www.\S+', '', text)
    text = re.sub(r'#\w+', '', text)
    complexity_score, avg_token_length = compute_text_complexity(text) if complexity is None else (complexity, 1.0)
    tokens = tokenize_text(text, complexity_score)
    text = " ".join(tokens)
    text = re.sub(r'[^\w\s\U0001F600-\U0001F64F]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text if text else "[EMPTY]"

def preprocess_data(df):
    df = df.copy()
    df.columns = df.columns.str.strip()
    logger.info(f"Dataset columns: {list(df.columns)}")
    print(f"Dataset columns: {list(df.columns)}")
    if 'content' not in df.columns:
        raise ValueError("Expected 'content' column in dataset")
    df = df.dropna(subset=['content']).reset_index(drop=True)
    tokenizer = AutoTokenizer.from_pretrained("UBC-NLP/MARBERT", use_fast=True, cache_dir='./cache')

    processed_texts = []
    valid_indices = []
    for idx, text in enumerate(tqdm(df['content'], desc="Preprocessing texts")):
        processed_text = preprocess_text(text)
        if processed_text == "[EMPTY]":
            logger.warning(f"Text at index {idx} is empty after preprocessing")
            continue
        enc = tokenizer(
            processed_text,
            padding=False,
            truncation=True,
            max_length=CONFIG['max_length'],
            return_tensors='pt'
        )
        input_ids = enc['input_ids'][0]
        valid_tokens = input_ids.ne(tokenizer.pad_token_id).sum().item() - 2
        if valid_tokens < CONFIG['min_valid_tokens']:
            logger.warning(f"Text at index {idx}: '{processed_text}' has too few valid tokens ({valid_tokens})")
            continue
        processed_texts.append(processed_text)
        valid_indices.append(idx)

    df = df.iloc[valid_indices].reset_index(drop=True)
    df['content'] = processed_texts

    emotion_cols = CONFIG['emotion_labels']
    for col in emotion_cols:
        if col not in df.columns:
            raise ValueError(f"Missing emotion column: {col}")
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)
        logger.info(f"{col} unique values after preprocessing: {df[col].unique()}")
        print(f"{col} unique values after preprocessing: {df[col].unique()}")
    no_labels = df[emotion_cols].sum(axis=1) == 0
    logger.info(f"Samples with no labels before filtering: {no_labels.sum()}")
    print(f"Samples with no labels before filtering: {no_labels.sum()}")
    df = df[~no_labels].reset_index(drop=True)
    logger.info(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    print(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    return df

def load_dataset(data_paths, results_dir):
    train_df = pd.read_excel(data_paths['train'])
    dev_df = pd.read_excel(data_paths['dev'])
    test_df = pd.read_excel(data_paths['test'])
    train_df.to_csv(os.path.join(results_dir, 'train_split.csv'), index=False)
    dev_df.to_csv(os.path.join(results_dir, 'dev_split.csv'), index=False)
    test_df.to_csv(os.path.join(results_dir, 'test_split.csv'), index=False)
    return train_df, dev_df, test_df

# ===============================
# PART 3: Model Components and Loss Functions
# ===============================

class LambdaNet(nn.Module):
    def __init__(self, input_dim=2):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 2),
            nn.Sigmoid()
        )

    def forward(self, x):
        lambdas = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        return lambdas

class AdaptiveGraphSAGELayer(nn.Module):
    def __init__(self, in_features, out_features, max_neighbors=10):
        super().__init__()
        self.fc_self = nn.Linear(in_features, out_features)
        self.fc_neigh = nn.Linear(in_features, out_features)
        self.norm = nn.LayerNorm(out_features)
        self.max_neighbors = max_neighbors
        self.aggregator_weights = nn.Parameter(torch.ones(3) / 3)

    def forward(self, h, adj, num_neighbors):
        batch_size = h.size(0)
        _, topk_indices = torch.topk(adj, min(num_neighbors, adj.size(1)), dim=1)
        h_neigh_mean = torch.zeros_like(h)
        h_neigh_max = torch.zeros_like(h)
        h_neigh_attn = torch.zeros_like(h)

        for i in range(batch_size):
            neigh_indices = topk_indices[i]
            if neigh_indices.numel() > 0:
                h_neigh_mean[i] = torch.mean(h[neigh_indices], dim=0)
                h_neigh_max[i] = torch.max(h[neigh_indices], dim=0)[0]
                attn_scores = F.softmax(torch.matmul(h[neigh_indices], h[i].unsqueeze(-1)), dim=0)
                h_neigh_attn[i] = torch.sum(h[neigh_indices] * attn_scores, dim=0)

        aggregator_weights = F.softmax(self.aggregator_weights, dim=0)
        h_neigh = (aggregator_weights[0] * h_neigh_mean +
                   aggregator_weights[1] * h_neigh_max +
                   aggregator_weights[2] * h_neigh_attn)

        h_self = self.fc_self(h)
        h_neigh = self.fc_neigh(h_neigh)
        h_prime = h_self + h_neigh
        h_prime = self.norm(F.relu(h_prime))
        return h_prime

class LossWeightNet(nn.Module):
    def __init__(self, input_dim=1):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 3),
            nn.Sigmoid()
        )
        self.prev_weights = None
        self.ema_alpha = CONFIG['ema_alpha']

    def forward(self, x):
        weights = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        if self.prev_weights is not None:
            weights = self.ema_alpha * self.prev_weights + (1 - self.ema_alpha) * weights
        self.prev_weights = weights.detach()
        return weights

class GTHLEmo(nn.Module):
    def __init__(self, num_emotions, embedding_dim=768, gcn_hidden_dim=768, gcn_layers=1, dropout_rate=0.1): # Added dropout_rate parameter
        super().__init__()
        self.num_emotions = num_emotions
        self.embedding_dim = embedding_dim
        self.gcn_layers = gcn_layers

        model_name = "UBC-NLP/MARBERT"
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True, cache_dir='./cache')
            self.transformer = AutoModel.from_pretrained(model_name, cache_dir='./cache')
        except Exception as e:
            logger.error(f"Failed to download {model_name}: {e}")
            raise RuntimeError(f"Ensure network connectivity or pre-download {model_name} to ./cache")

        self.attention_weight = nn.Parameter(torch.randn(embedding_dim))
        self.attention_bias = nn.Parameter(torch.tensor(0.0))
        self.attention_fc = nn.Linear(embedding_dim, embedding_dim)
        self.dropout = nn.Dropout(dropout_rate) # Initialized dropout layer

        self.gcn_layers_list = nn.ModuleList([
            AdaptiveGraphSAGELayer(embedding_dim if i == 0 else gcn_hidden_dim, gcn_hidden_dim, CONFIG['graphsage_neighbors'])
            for i in range(gcn_layers)
        ])

        self.fusion_fc = nn.Linear(embedding_dim * 2, embedding_dim)
        self.fusion_norm = nn.LayerNorm(embedding_dim)

        self.label_embeddings = nn.Parameter(torch.randn(num_emotions, embedding_dim))
        self.label_transformer_layers = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=embedding_dim,
                nhead=CONFIG['label_transformer_heads'],
                dim_feedforward=512,
                dropout=0.1,
                batch_first=True
            ) for _ in range(CONFIG['label_transformer_layers'])
        ])

        self.classifier = nn.Linear(embedding_dim, num_emotions)
        self.classifier_bias = nn.Parameter(torch.zeros(num_emotions))

        self.lambda_net = LambdaNet().to(device)
        self.loss_weight_net = LossWeightNet().to(device)
        self.emoji_cooccurrence = {}
        self.emoji_embeddings = nn.ParameterDict()

        self.loss_fn = hybrid_loss(
            focal_lambda=CONFIG['focal_lambda'],
            graph_lambda=CONFIG['graph_lambda'],
            ranking_lambda=CONFIG['ranking_lambda'],
            num_emotions=num_emotions,
            similarity_threshold=CONFIG['similarity_threshold']
        )

        self.to(device)

    def update_emoji_embeddings(self, texts, labels):
        for text, label in zip(texts, labels):
            emojis = re.findall(r'\U0001F600-\U0001F64F', text)
            for e in emojis:
                if e not in self.emoji_cooccurrence:
                    self.emoji_cooccurrence[e] = np.zeros(self.num_emotions)
                for i, val in enumerate(label):
                    if val == 1:
                        self.emoji_cooccurrence[e][i] += 1
        for e in self.emoji_cooccurrence:
            if e not in self.emoji_embeddings:
                embedding = torch.randn(self.embedding_dim, device=device, requires_grad=True)
                self.emoji_embeddings[e] = nn.Parameter(embedding)
            else:
                counts = torch.tensor(self.emoji_cooccurrence[e], dtype=torch.float32, device=device)
                norm_counts = counts / (counts.sum() + 1e-7)
                emotion_emb = self.label_embeddings @ norm_counts
                self.emoji_embeddings[e].data = 0.9 * self.emoji_embeddings[e].data + 0.1 * emotion_emb

    def preprocess_with_emoji(self, text):
        if not isinstance(text, str) or not text.strip():
            return "[EMPTY]"
        for emoji_char, embedding in self.emoji_embeddings.items():
            if emoji_char in text:
                emotion_idx = torch.topk(torch.matmul(F.normalize(embedding, dim=0), F.normalize(self.label_embeddings, dim=1).t()), 1).indices.item()
                emotion_word = CONFIG['emotion_labels'][emotion_idx]
                text = text.replace(emoji_char, f" {emotion_word} ")
        return preprocess_text(text)

    def prepare_inputs(self, texts):
        valid_texts = [self.preprocess_with_emoji(t) for t in texts if isinstance(t, str) and t.strip() and self.preprocess_with_emoji(t) != "[EMPTY]"]
        if not valid_texts:
            logger.warning("No valid texts in batch; returning dummy input")
            return {'input_ids': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device)}
        try:
            enc = self.tokenizer(
                valid_texts,
                padding='max_length',
                truncation=True,
                max_length=CONFIG['max_length'],
                return_tensors='pt',
                return_attention_mask=True
            )
            input_ids = enc['input_ids']
            attention_mask = enc['attention_mask']
            return {'input_ids': input_ids.to(device), 'attention_mask': attention_mask.to(device)}
        except Exception as e:
            logger.error(f"Tokenization failed: {e}")
            return {'input_ids': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device)}

    def compute_adjacency(self, h_span, labels=None):
        batch_size = h_span.size(0)
        if batch_size <= 1:
            return torch.eye(batch_size, device=h_span.device), 1.0
        h_span_norm = F.normalize(h_span, dim=1)
        cosine_sim = torch.matmul(h_span_norm, h_span_norm.t()).cpu().detach().numpy()
        similarity_threshold = np.percentile(cosine_sim.flatten(), 75) if cosine_sim.size > 1 else CONFIG['similarity_threshold']

        if labels is None:
            sim = cosine_sim
        else:
            labels_np = labels.cpu().numpy()
            jaccard_sim = np.zeros((batch_size, batch_size))
            for i in range(batch_size):
                for j in range(batch_size):
                    jaccard_sim[i, j] = jaccard_score(labels_np[i], labels_np[j], zero_division=0)
            mean_cosine = np.mean(cosine_sim)
            label_entropy = entropy(labels_np.sum(axis=0) / (labels_np.sum() + 1e-7))
            lambda_inputs = torch.tensor([mean_cosine, label_entropy], dtype=torch.float32, device=h_span.device).unsqueeze(0)
            lambda1, lambda2 = self.lambda_net(lambda_inputs)[0]
            sim = lambda1.item() * jaccard_sim + lambda2.item() * cosine_sim

        adj = sparse.csr_matrix((sim > similarity_threshold).astype(float))
        adj = adj + sparse.eye(batch_size, format='csr')
        degree = np.array(adj.sum(axis=1)).flatten()
        degree_inv_sqrt = sparse.diags(1.0 / np.sqrt(degree + 1e-7))
        adj_norm = degree_inv_sqrt @ adj @ degree_inv_sqrt
        return torch.tensor(adj_norm.toarray(), dtype=torch.float32, device=h_span.device), degree.mean()

    def forward(self, texts, labels=None, training=True, return_spans=False):
        if training and labels is not None:
            self.update_emoji_embeddings(texts, labels.cpu().numpy())
        inputs = self.prepare_inputs(texts)
        outputs = self.transformer(input_ids=inputs['input_ids'], attention_mask=inputs['attention_mask'])
        hidden_states = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']

        scores = torch.matmul(hidden_states, self.attention_weight) + self.attention_bias
        scores = torch.clamp(scores, -1e4, 1e4)
        scores = scores.masked_fill(attention_mask == 0, -1e4)
        alpha = F.softmax(scores, dim=1)
        h_span = torch.sum(hidden_states * alpha.unsqueeze(-1), dim=1)
        h_span = self.attention_fc(h_span)
        h_span = self.dropout(h_span) # Applied dropout to h_span

        adj, avg_degree = self.compute_adjacency(h_span, labels)
        num_neighbors = max(2, min(CONFIG['graphsage_neighbors'], int(avg_degree)))

        h_graph = h_span
        for layer in self.gcn_layers_list:
            h_graph = layer(h_graph, adj, num_neighbors)

        h_fused = torch.cat([h_span, h_graph], dim=-1)
        h_fused = self.fusion_norm(F.relu(self.fusion_fc(h_fused)))
        h_fused = self.dropout(h_fused) # Applied dropout to h_fused

        label_emb = self.label_embeddings.unsqueeze(1)
        for layer in self.label_transformer_layers:
            label_emb = layer(label_emb)
        label_emb = label_emb.squeeze(1)

        logits = self.classifier(h_fused) + self.classifier_bias
        y_hat = torch.sigmoid(logits)

        if return_spans:
            span_scores = torch.einsum('bld,cd->blc', hidden_states, label_emb)
            span_attn = F.softmax(span_scores.masked_fill(attention_mask.unsqueeze(-1) == 0, -1e4), dim=1)
            return y_hat, span_attn, inputs['input_ids']
        return y_hat

class hybrid_loss(nn.Module):
    def __init__(self, focal_lambda=0.1, graph_lambda=0.1, ranking_lambda=0.1, num_emotions=11, similarity_threshold=0.5):
        super().__init__()
        self.base_focal_lambda = focal_lambda
        self.base_graph_lambda = graph_lambda
        self.base_ranking_lambda = ranking_lambda
        self.num_emotions = num_emotions
        self.similarity_threshold = similarity_threshold
        self.margin = 0.5

    def bce_loss(self, y_pred, y_true):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        return -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()

    def focal_loss(self, y_pred, y_true, alpha=0.25, gamma=2.0):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        pt = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        focal = -alpha * (1 - pt) ** gamma * torch.log(pt)
        return focal.mean()

    def ranking_loss(self, y_pred, y_true):
        batch_size, num_labels = y_pred.size()
        loss = torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        for i in range(batch_size):
            pos_indices = y_true[i].nonzero(as_tuple=True)[0]
            neg_indices = (1 - y_true[i]).nonzero(as_tuple=True)[0]
            if len(pos_indices) == 0 or len(neg_indices) == 0:
                continue
            pos_scores = y_pred[i, pos_indices]
            neg_scores = y_pred[i, neg_indices]
            diff = pos_scores.unsqueeze(1) - neg_scores.unsqueeze(0)
            loss = loss + F.relu(self.margin - diff).mean()
        return loss / (batch_size + 1e-7)

    def graph_kl_loss(self, label_emb, y_true):
        A = torch.matmul(y_true.t(), y_true) / (y_true.size(0) + 1e-7)
        L_norm = F.normalize(label_emb, dim=1)
        Q = torch.matmul(L_norm, L_norm.t())
        A = F.softmax(A, dim=1)
        Q = F.softmax(Q, dim=1)
        kl = F.kl_div(Q.log(), A, reduction='batchmean')
        return torch.clamp(kl, 0, 10)

    def compute_adaptive_focal_params(self, y_true):
        class_counts = y_true.sum(dim=0).cpu().numpy()
        total = y_true.sum().item() + 1e-7
        class_freq = class_counts / total
        alpha = 1.0 - class_freq / (class_freq.max() + 1e-7)
        alpha = np.clip(alpha, 0.1, 0.9)
        gamma = 2.0 + 2.0 * entropy(class_freq)
        return alpha.mean(), min(gamma, 4.0)


    def forward(self, y_pred, y_true, label_emb=None, loss_weight_net=None, jaccard_score=None):
        bce = self.bce_loss(y_pred, y_true)
        alpha, gamma = self.compute_adaptive_focal_params(y_true)
        focal = self.focal_loss(y_pred, y_true, alpha, gamma)
        ranking = self.ranking_loss(y_pred, y_true)
        graph_kl = self.graph_kl_loss(label_emb, y_true) if label_emb is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)

        if loss_weight_net is not None and jaccard_score is not None:
            # Get adaptive weights
            weights = loss_weight_net(torch.tensor([jaccard_score], dtype=torch.float32, device=y_pred.device).unsqueeze(0))
            focal_lambda, graph_lambda, ranking_lambda = weights[0]
        else:
            # Use static base weights
            focal_lambda = self.base_focal_lambda
            graph_lambda = self.base_graph_lambda
            ranking_lambda = self.base_ranking_lambda

        # Ensure lambdas are tensors for calculation but return them as scalar/tensor for logging
        if not isinstance(focal_lambda, torch.Tensor): focal_lambda = torch.tensor(focal_lambda, device=y_pred.device)
        if not isinstance(graph_lambda, torch.Tensor): graph_lambda = torch.tensor(graph_lambda, device=y_pred.device)
        if not isinstance(ranking_lambda, torch.Tensor): ranking_lambda = torch.tensor(ranking_lambda, device=y_pred.device)

        total_loss = bce + focal_lambda * focal + ranking_lambda * ranking + graph_lambda * graph_kl

        # RETURN THE LAMBDAS AT THE END
        return total_loss, bce, focal, ranking, graph_kl, focal_lambda, graph_lambda, ranking_lambda

from tqdm import tqdm

def train_model(model, train_texts, val_texts, train_labels, val_labels, weights_file):
    print("Training full model...")
    logger.info("Training model")
    optimizer = optim.AdamW(model.parameters(), lr=CONFIG['learning_rate'], weight_decay=CONFIG['weight_decay'])
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=3)
    scaler = GradScaler()
    best_val_jaccard = 0
    patience_counter = 0
    history = {
        'loss': [], 'val_loss': [],
        'bce_loss': [], 'val_bce_loss': [],
        'focal_loss': [], 'val_focal_loss': [],
        'ranking_loss': [], 'val_ranking_loss': [],
        'graph_kl_loss': [], 'val_graph_kl_loss': [],
        'jaccard': [], 'val_jaccard': []
    }

    train_batches = (len(train_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    val_batches = (len(val_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']

    for epoch in range(CONFIG['epochs']):
        model.train()
        train_loss = train_bce_loss = train_focal_loss = train_ranking_loss = train_graph_kl_loss = train_jaccard = 0
        valid_train_batches = 0

        train_pbar = tqdm(range(train_batches), desc=f"Epoch {epoch+1} Training", leave=True, ncols=90)
        for i in train_pbar:
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(train_texts))
            batch_texts = train_texts[start:end]
            batch_labels = train_labels[start:end]

            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                continue

            batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

            optimizer.zero_grad()
            with autocast(device_type=device_type):
                try:
                    y_hat = model(batch_texts, labels=batch_labels)
                    loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                        y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                        train_jaccard / max(valid_train_batches, 1)
                    )
                except Exception as e:
                    continue

            if torch.isnan(loss) or torch.isinf(loss):
                continue

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
            scaler.step(optimizer)
            scaler.update()

            preds = (y_hat.detach() > 0.5).float()
            batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

            train_loss += loss.item()
            train_bce_loss += bce_loss.item()
            train_focal_loss += focal_loss.item()
            train_ranking_loss += ranking_loss.item()
            train_graph_kl_loss += graph_kl_loss.item()
            train_jaccard += batch_jaccard
            valid_train_batches += 1

            # Update progress bar every 10 steps or last batch
            if valid_train_batches > 0 and ((i % 10 == 0) or (i == train_batches - 1)):
                avg_jaccard = train_jaccard / valid_train_batches
                train_pbar.set_postfix({'Avg Jaccard': f"{avg_jaccard:.4f}"})

            torch.cuda.empty_cache()

        if valid_train_batches > 0:
            train_loss /= valid_train_batches
            train_bce_loss /= valid_train_batches
            train_focal_loss /= valid_train_batches
            train_ranking_loss /= valid_train_batches
            train_graph_kl_loss /= valid_train_batches
            train_jaccard /= valid_train_batches

        # Validation
        model.eval()
        val_loss = val_bce_loss = val_focal_loss = val_ranking_loss = val_graph_kl_loss = val_jaccard = 0
        valid_val_batches = 0

        val_pbar = tqdm(range(val_batches), desc=f"Epoch {epoch+1} Validation", leave=True, ncols=90)
        with torch.no_grad():
            for i in val_pbar:
                start = i * CONFIG['batch_size']
                end = min(start + CONFIG['batch_size'], len(val_texts))
                batch_texts = val_texts[start:end]
                batch_labels = val_labels[start:end]

                if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                    continue

                batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

                with autocast(device_type=device_type):
                    try:
                        y_hat = model(batch_texts, labels=batch_labels)
                        loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                            y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                            val_jaccard / max(valid_val_batches, 1)
                        )
                    except Exception as e:
                        continue

                preds = (y_hat.detach() > 0.5).float()
                batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

                val_loss += loss.item()
                val_bce_loss += bce_loss.item()
                val_focal_loss += focal_loss.item()
                val_ranking_loss += ranking_loss.item()
                val_graph_kl_loss += graph_kl_loss.item()
                val_jaccard += batch_jaccard
                valid_val_batches += 1

                if valid_val_batches > 0 and ((i % 10 == 0) or (i == val_batches - 1)):
                    avg_val_jaccard = val_jaccard / valid_val_batches
                    val_pbar.set_postfix({'Avg Jaccard': f"{avg_val_jaccard:.4f}"})

                torch.cuda.empty_cache()

        if valid_val_batches > 0:
            val_loss /= valid_val_batches
            val_bce_loss /= valid_val_batches
            val_focal_loss /= valid_val_batches
            val_ranking_loss /= valid_val_batches
            val_graph_kl_loss /= valid_val_batches
            val_jaccard /= valid_val_batches

        print(f"\nEpoch {epoch+1} Summary:")
        print(f"Train Loss: {train_loss:.4f} (BCE: {train_bce_loss:.4f}, Focal: {train_focal_loss:.4f}, Ranking: {train_ranking_loss:.4f}, Graph KL: {train_graph_kl_loss:.4f})")
        print(f"Train Jaccard: {train_jaccard:.4f}")
        print(f"Val Loss: {val_loss:.4f} (BCE: {val_bce_loss:.4f}, Focal: {val_focal_loss:.4f}, Ranking: {val_ranking_loss:.4f}, Graph KL: {val_graph_kl_loss:.4f})")
        print(f"Val Jaccard: {val_jaccard:.4f}")

        history['loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['bce_loss'].append(train_bce_loss)
        history['val_bce_loss'].append(val_bce_loss)
        history['focal_loss'].append(train_focal_loss)
        history['val_focal_loss'].append(val_focal_loss)
        history['ranking_loss'].append(train_ranking_loss)
        history['val_ranking_loss'].append(val_ranking_loss)
        history['graph_kl_loss'].append(train_graph_kl_loss)
        history['val_graph_kl_loss'].append(val_graph_kl_loss)
        history['jaccard'].append(train_jaccard)
        history['val_jaccard'].append(val_jaccard)

        scheduler.step()

        if val_jaccard > best_val_jaccard:
            best_val_jaccard = val_jaccard
            if check_disk_space(CONFIG['results_dir']):
                torch.save(model.state_dict(), weights_file)
                print(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
                logger.info(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= CONFIG['patience']:
                print(f"Early stopping at epoch {epoch+1}")
                logger.info(f"Early stopping at epoch {epoch+1}")
                break

        check_disk_space(CONFIG['results_dir'])

    if os.path.exists(weights_file):
        model.load_state_dict(torch.load(weights_file))
        print(f"Loaded best model from {weights_file}")
        logger.info(f"Loaded best model from {weights_file}")
    else:
        print(f"No saved model found at {weights_file}")
        logger.warning(f"No saved model found at {weights_file}")

    pd.DataFrame(history).to_csv(os.path.join(CONFIG['results_dir'], 'training_history.csv'), index=False)
    return model, history

from tqdm import tqdm

def evaluate_classifier(model, texts, labels, split='test'):
    logger.info(f"Evaluating classifier on {split} split")
    print(f"Evaluating classifier on {split} split")
    model.eval()
    num_batches = (len(texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    preds_proba = []
    span_attns = []
    input_ids_list = []

    with torch.no_grad():
        eval_pbar = tqdm(range(num_batches), desc=f"{split.capitalize()} Eval", leave=True, ncols=80)
        for i in eval_pbar:
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(texts))
            batch_texts = texts[start:end]
            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                continue
            with autocast(device_type=device_type):
                try:
                    y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                    preds_proba.append(y_hat.cpu().float())
                    span_attns.append(span_attn.cpu())
                    input_ids_list.append(input_ids.cpu())
                except Exception as e:
                    continue
            torch.cuda.empty_cache()

    if not preds_proba:
        logger.warning(f"No valid predictions for {split} split")
        return {}, {}, np.zeros_like(labels), {}, {}

    preds_proba = torch.cat(preds_proba, dim=0).numpy()
    span_attn = torch.cat(span_attns, dim=0)
    input_ids = torch.cat(input_ids_list, dim=0)
    labels = np.array(labels)

    thresholds = np.arange(0.1, 0.5, 0.01)
    best_thresholds = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        best_jaccard = 0
        best_t = 0.5
        for t in thresholds:
            preds = (preds_proba[:, i] >= t).astype(int)
            j = jaccard_score(labels[:, i], preds, zero_division=0)
            if j > best_jaccard:
                best_jaccard = j
                best_t = t
        best_thresholds[label] = best_t

    preds = np.zeros_like(preds_proba)
    for i, label in enumerate(CONFIG['emotion_labels']):
        preds[:, i] = (preds_proba[:, i] >= best_thresholds[label]).astype(int)

    ap_scores = []
    no_positive_labels = []
    for i, label in enumerate(CONFIG['emotion_labels']):
        positive_count = np.sum(labels[:, i])
        logger.info(f"{split} set - {label}: {positive_count} positive samples")
        print(f"{split} set - {label}: {positive_count} positive samples")
        if positive_count == 0:
            logger.warning(f"No positive samples for label {label} in {split} set; skipping Average Precision")
            no_positive_labels.append(label)
            continue
        ap = average_precision_score(labels[:, i], preds_proba[:, i])
        if not np.isnan(ap):
            ap_scores.append(ap)

    metrics = {
        'jaccard': jaccard_score(labels, preds, average='samples', zero_division=0),
        'hamming_loss': hamming_loss(labels, preds),
        'precision': precision_score(labels, preds, average='samples', zero_division=0),
        'recall': recall_score(labels, preds, average='samples', zero_division=0),
        'f1': f1_score(labels, preds, average='samples', zero_division=0),
        'micro_precision': precision_score(labels, preds, average='micro', zero_division=0),
        'micro_recall': recall_score(labels, preds, average='micro', zero_division=0),
        'micro_f1': f1_score(labels, preds, average='micro', zero_division=0),
        'macro_precision': precision_score(labels, preds, average='macro', zero_division=0),
        'macro_recall': recall_score(labels, preds, average='macro', zero_division=0),
        'macro_f1': f1_score(labels, preds, average='macro', zero_division=0),
        'mean_average_precision': np.mean(ap_scores) if ap_scores else np.nan
    }

    class_metrics = {}
    confusion_matrices = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        class_metrics[label] = {
            'precision': precision_score(labels[:, i], preds[:, i], zero_division=0),
            'recall': recall_score(labels[:, i], preds[:, i], zero_division=0),
            'f1': f1_score(labels[:, i], preds[:, i], zero_division=0),
            'average_precision': average_precision_score(labels[:, i], preds_proba[:, i]) if np.sum(labels[:, i]) > 0 else np.nan,
            'threshold': best_thresholds[label]
        }
        cm = confusion_matrix(labels[:, i], preds[:, i])
        confusion_matrices[label] = cm

    return metrics, class_metrics, preds, best_thresholds, confusion_matrices

def compute_correlation_matrices(gt_labels, pred_labels, emotion_labels, results_dir):
    gt_labels = np.array(gt_labels)
    pred_labels = np.array(pred_labels)
    gt_corr = np.corrcoef(gt_labels.T)
    pred_corr = np.corrcoef(pred_labels.T)
    gt_corr = np.nan_to_num(gt_corr, nan=0.0)
    pred_corr = np.nan_to_num(pred_corr, nan=0.0)

    # No visualization, just save numeric matrices if needed
    np.save(os.path.join(results_dir, 'gt_correlation_matrix.npy'), gt_corr)
    np.save(os.path.join(results_dir, 'pred_correlation_matrix.npy'), pred_corr)

    return gt_corr, pred_corr

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import pandas as pd
import numpy as np

# ---------------------------------------------------------
# 1. The MDPI Formatter Rule
# ---------------------------------------------------------
def mdpi_tick_format(x, pos):
    """
    MDPI Rule: Use commas for numbers with 5 or more digits (10,000),
    but NO commas for 4 digits (5000).
    """
    if x >= 10000 or x <= -10000:
        return f"{int(x):,}"  # Adds comma (e.g., 10,000)
    else:
        return f"{int(x)}"    # No comma (e.g., 5000)

def plot_mdpi_lambda_dynamics(save_path="lamda_corrected.png"):
    fig, ax = plt.subplots(figsize=(10, 6), dpi=300)

    # ---------------------------------------------------------
    # 2. Load Your Data
    # ---------------------------------------------------------
    # IMPORTANT: Replace the dummy data block below with your actual CSV loading code.
    # Example:
    # df = pd.read_csv("your_training_logs.csv")
    # steps = df['steps']
    # l_focal = df['lambda_focal']
    # l_corr = df['lambda_corr']
    # l_rank = df['lambda_rank']

    # --- DUMMY DATA (To mimic your image so the script runs) ---
    steps = np.arange(0, 22500, 10)
    l_focal = np.clip(0.555 - (steps // 2200) * 0.006, 0.515, 0.555)
    l_rank = np.clip(0.60 - (steps // 3200) * 0.01, 0.54, 0.60)
    l_corr = 0.53 - (steps / 22500)**0.8 * 0.25
    l_corr = np.round(l_corr * 150) / 150
    l_corr += np.where(steps % 500 == 0, 0.015, 0) # Mimic spikes
    # ---------------------------------------------------------

    # 3. Plot the curves
    ax.plot(steps, l_focal, label=r'$\lambda_{focal}$', color='#1f77b4', linewidth=1.5)
    ax.plot(steps, l_corr, label=r'$\lambda_{corr}$', color='#ff7f0e', linewidth=1.5)
    ax.plot(steps, l_rank, label=r'$\lambda_{rank}$', color='#2ca02c', linewidth=1.5)

    # 4. Apply MDPI Formatting to the X-axis
    ax.xaxis.set_major_formatter(FuncFormatter(mdpi_tick_format))

    # Ensure ticks fall at the exact intervals shown in your image
    ax.set_xticks([0, 5000, 10000, 15000, 20000])

    # 5. Aesthetics matching your original image
    ax.set_title('Evolution of Adaptive Loss Weights During Training', fontsize=14)
    ax.set_xlabel('Training Steps', fontsize=12)
    ax.set_ylabel('Adaptive Weight Value', fontsize=12)

    # Grid
    ax.grid(True, linestyle='--', alpha=0.5, color='lightgray')

    # Legend
    ax.legend(loc='upper right', fontsize=11, framealpha=1.0)

    # Save
    plt.savefig(save_path, bbox_inches='tight', dpi=300)
    print(f"Figure successfully saved to {save_path} with MDPI formatting.")
    plt.show()

if __name__ == "__main__":
    plot_mdpi_lambda_dynamics()

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Exact labels
labels = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love',
          'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

# 2. Exact data transcribed from your original 'gt_correlation_matrix.png'
gt_data = np.array([
    [1.00, 0.03, 0.47, -0.05, -0.44, -0.40, -0.39, 0.18, 0.09, -0.01, -0.15],
    [0.03, 1.00, -0.01, 0.14, -0.09, -0.10, -0.04, 0.00, -0.05, 0.04, 0.02],
    [0.47, -0.01, 1.00, -0.10, -0.27, -0.27, -0.25, 0.20, 0.01, -0.01, -0.08],
    [-0.05, 0.14, -0.10, 1.00, -0.25, -0.21, -0.18, 0.01, -0.01, 0.01, -0.05],
    [-0.44, -0.09, -0.27, -0.25, 1.00, 0.61, 0.58, -0.28, -0.43, 0.06, 0.16],
    [-0.40, -0.10, -0.27, -0.21, 0.61, 1.00, 0.55, -0.28, -0.30, -0.01, 0.16],
    [-0.39, -0.04, -0.25, -0.18, 0.58, 0.55, 1.00, -0.28, -0.33, -0.02, 0.21],
    [0.18, 0.00, 0.20, 0.01, -0.28, -0.28, -0.28, 1.00, 0.30, 0.01, -0.11],
    [0.09, -0.05, 0.01, -0.01, -0.43, -0.30, -0.33, 0.30, 1.00, -0.04, -0.16],
    [-0.01, 0.04, -0.01, 0.01, 0.06, -0.01, -0.02, 0.01, -0.04, 1.00, 0.00],
    [-0.15, 0.02, -0.08, -0.05, 0.16, 0.16, 0.21, -0.11, -0.16, 0.00, 1.00]
])

# 3. Exact data transcribed from your original 'pred_correlation_matrix.png'
pred_data = np.array([
    [1.00, -0.14, 0.68, -0.14, -0.55, -0.52, -0.54, 0.29, 0.11, -0.05, -0.19],
    [-0.14, 1.00, -0.19, 0.35, -0.06, -0.17, -0.06, -0.03, -0.13, 0.20, 0.08],
    [0.68, -0.19, 1.00, -0.25, -0.38, -0.36, -0.37, 0.19, -0.12, -0.04, -0.14],
    [-0.14, 0.35, -0.25, 1.00, -0.26, -0.25, -0.24, -0.04, 0.09, 0.03, -0.05],
    [-0.55, -0.06, -0.38, -0.26, 1.00, 0.78, 0.75, -0.40, -0.48, 0.06, 0.14],
    [-0.52, -0.17, -0.36, -0.25, 0.78, 1.00, 0.76, -0.43, -0.41, -0.07, 0.13],
    [-0.54, -0.06, -0.37, -0.24, 0.75, 0.76, 1.00, -0.42, -0.41, -0.04, 0.27],
    [0.29, -0.03, 0.19, -0.04, -0.40, -0.43, -0.42, 1.00, 0.34, 0.04, -0.17],
    [0.11, -0.13, -0.12, 0.09, -0.48, -0.41, -0.41, 0.34, 1.00, -0.12, -0.18],
    [-0.05, 0.20, -0.04, 0.03, 0.06, -0.07, -0.04, 0.04, -0.12, 1.00, 0.03],
    [-0.19, 0.08, -0.14, -0.05, 0.14, 0.13, 0.27, -0.17, -0.18, 0.03, 1.00]
])

def plot_and_save_matrix(data, title, filename):
    fig, ax = plt.subplots(figsize=(10, 8), dpi=300)

    # Format annotations to replace hyphen with unicode minus (U+2212)
    annot_labels = np.array([[f"{val:.2f}".replace('-', '\u2212') for val in row] for row in data])

    # Plot heatmap
    heatmap = sns.heatmap(data, annot=annot_labels, fmt="", cmap="Blues",
                          xticklabels=labels, yticklabels=labels, ax=ax)

    # Format the colorbar ticks to use unicode minus
    cbar = heatmap.collections[0].colorbar
    ticks = cbar.get_ticks()
    cbar.set_ticks(ticks)
    cbar.set_ticklabels([f"{t:.1f}".replace('-', '\u2212') for t in ticks])

    ax.set_title(title)

    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    print(f"Saved: {filename}")
    plt.show()

# Generate and save both figures
plot_and_save_matrix(gt_data, "Ground Truth Correlation Matrix", "gt_correlation_matrix.png")
plot_and_save_matrix(pred_data, "Predicted Correlation Matrix", "pred_correlation_matrix.png")