# -*- coding: utf-8 -*-
"""GTHL-Emo_Proposed_Model-EXAAEC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di2BB8qps42VlU9oxRqg1i_l_rd54-LU
"""

!pip install Emoji
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model
import re
from tqdm import tqdm
import logging
from sklearn.metrics import jaccard_score, f1_score, precision_score, recall_score, confusion_matrix, average_precision_score, hamming_loss
import json
import matplotlib.pyplot as plt
import seaborn as sns
from torch.amp import GradScaler, autocast
from scipy import sparse
from scipy.stats import entropy
import shutil
import urllib3
import emoji
import time
from sklearn.model_selection import train_test_split

# Disable urllib3 warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Configuration
CONFIG = {
    'seed': 42,
    'max_length': 128,
    'batch_size': 8,
    'epochs': 10,
    'learning_rate': 2e-5,
    'weight_decay': 0.02,
    'patience': 7,
    'data_paths': {
        'dataset': './ExaAEC-dataset.xlsx',
    },
    'results_dir': './results/',
    'emotion_labels': ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'acceptance', 'sadness', 'surprise', 'neutral'],
    'lora_rank': 16,
    'embedding_dim': 768,
    'focal_lambda': 0.1,
    'graph_lambda': 0.1,
    'ranking_lambda': 0.1,
    'temperature': 0.07,
    'mc_dropout_samples': 5,
    'gcn_hidden_dim': 768,
    'similarity_threshold': 0.5,
    'min_lambda': 0.05,
    'ema_alpha': 0.95,
    'gcn_layers': 1,
    'top_k_spans': 5,
    'lambda1': 0.5,
    'lambda2': 0.5,
    'graphsage_neighbors': 5,
    'label_transformer_layers': 2,
    'label_transformer_heads': 8,
    'verbose_logging': True,
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    'min_valid_tokens': 3
}

# Emoji mapping
emoji_map = {
    '😠': 'غاضب', '😡': 'غاضب', '🤬': 'غاضب', '💢': 'غاضب', '😤': 'غاضب', '😾': 'غاضب', '💪': 'غاضب',
    '🤔': 'مترقب', '👀': 'مترقب', '🕐': 'مترقب', '⏳': 'مترقب', '🎯': 'مترقب', '🔍': 'مترقب',
    '🤢': 'مقرف', '🤮': 'مقرف', '🤧': 'مقرف', '😫': 'مقرف', '🥴': 'مقرف',
    '😨': 'خائف', '😱': 'خائف', '😰': 'خائف', '😥': 'خائف', '🥶': 'خائف', '😖': 'خائف',
    '😊': 'سعيد', '😃': 'سعيد', '😄': 'سعيد', '😁': 'سعيد', '🤗': 'سعيد', '😂': 'سعيد', '🤣': 'سعيد',
    '😅': 'سعيد', '😆': 'سعيد', '🎉': 'سعيد', '✨': 'سعيد',
    '❤️': 'محب', '💕': 'محب', '💗': 'محب', '💖': 'محب', '🥰': 'محب', '😍': 'محب', '😘': 'محب',
    '💝': 'محب', '💑': 'محب',
    '😔': 'حزين', '😕': 'حزين', '😩': 'حزين', '🥺': 'حزين', '😣': 'حزين', '😟': 'حزين', '🤦': 'حزين', '👎': 'حزين',
    '😢': 'حزين', '😭': 'حزين', '😥': 'حزين', '💔': 'حزين', '😪': 'حزين', '🥀': 'حزين', '😿': 'حزين', '😴': 'حزين', '🎭': 'حزين',
    '😮': 'مندهش', '😯': 'مندهش', '😲': 'مندهش', '😳': 'مندهش', '🤯': 'مندهش', '😱': 'مندهش',
    '😐': 'محايد', '😑': 'محايد', '😶': 'محايد', '🙂': 'محايد', '😬': 'محايد'
}

# Setup directories and logging
os.makedirs(CONFIG['results_dir'], exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(CONFIG['results_dir'], 'pipeline.log')),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger()

# Set random seed
def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_random_seed(CONFIG['seed'])
device = torch.device(CONFIG['device'])
device_type = CONFIG['device']
print(f"Using device: {device} (device_type: {device_type})")
logger.info(f"Using device: {device} (device_type: {device_type})")

# Disk space management
def check_disk_space(path):
    stat = shutil.disk_usage(path)
    free_space = stat.free / (1024 ** 3)  # Free space in GB
    logger.info(f"Free disk space in {path}: {free_space:.2f} GB")
    print(f"Free disk space in {path}: {free_space:.2f} GB")
    return free_space > 1

def cleanup_old_models(directory):
    for file in os.listdir(directory):
        if file.endswith('.pth'):
            try:
                os.remove(os.path.join(directory, file))
                logger.info(f"Removed old model file: {file}")
                print(f"Removed old model file: {file}")
            except Exception as e:
                logger.warning(f"Failed to remove {file}: {e}")
                print(f"Failed to remove {file}: {e}")

# Preprocessing
def compute_text_complexity(text):
    tokens = tokenize_text(text)
    unique_tokens = len(set(tokens))
    avg_token_length = np.mean([len(t) for t in tokens]) if tokens else 1.0
    return unique_tokens / len(tokens) if tokens else 0.0, avg_token_length

def tokenize_text(text, complexity=0.5):
    if complexity > 0.7:
        tokens = re.findall(r'\w+|[^\w\s]', text, re.UNICODE)
    else:
        tokens = text.split()
    return tokens

def preprocess_text(text, complexity=None):
    if not isinstance(text, str) or not text.strip():
        return "[EMPTY]"
    for emoji_char, emotion_word in emoji_map.items():
        text = text.replace(emoji_char, f" {emotion_word} ")
    text = emoji.demojize(text, language='ar')
    text = re.sub(r'http\S+|www.\S+', '', text)
    text = re.sub(r'#\w+', '', text)
    complexity_score, avg_token_length = compute_text_complexity(text) if complexity is None else (complexity, 1.0)
    tokens = tokenize_text(text, complexity_score)
    text = " ".join(tokens)
    text = re.sub(r'[^\w\s\U0001F600-\U0001F64F]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text if text else "[EMPTY]"

def preprocess_data(df):
    df = df.copy()
    df.columns = df.columns.str.strip()
    logger.info(f"Dataset columns: {list(df.columns)}")
    print(f"Dataset columns: {list(df.columns)}")
    if 'content' not in df.columns:
        raise ValueError("Expected 'content' column in dataset")
    df = df.dropna(subset=['content']).reset_index(drop=True)
    tokenizer = AutoTokenizer.from_pretrained("UBC-NLP/MARBERT", use_fast=True, cache_dir='./cache')

    # Preprocess texts and check token count
    processed_texts = []
    valid_indices = []
    for idx, text in enumerate(tqdm(df['content'], desc="Preprocessing texts")):
        processed_text = preprocess_text(text)
        if processed_text == "[EMPTY]":
            logger.warning(f"Text at index {idx} is empty after preprocessing")
            continue
        # Tokenize to check valid token count
        enc = tokenizer(
            processed_text,
            padding=False,
            truncation=True,
            max_length=CONFIG['max_length'],
            return_tensors='pt'
        )
        input_ids = enc['input_ids'][0]
        valid_tokens = input_ids.ne(tokenizer.pad_token_id).sum().item() - 2  # Exclude [CLS], [SEP]
        if valid_tokens < CONFIG['min_valid_tokens']:
            logger.warning(f"Text at index {idx}: '{processed_text}' has too few valid tokens ({valid_tokens})")
            continue
        processed_texts.append(processed_text)
        valid_indices.append(idx)

    df = df.iloc[valid_indices].reset_index(drop=True)
    df['content'] = processed_texts

    # Remove samples with no labels
    emotion_cols = CONFIG['emotion_labels']
    for col in emotion_cols:
        if col not in df.columns:
            raise ValueError(f"Missing emotion column: {col}")
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)
        logger.info(f"{col} unique values after preprocessing: {df[col].unique()}")
        print(f"{col} unique values after preprocessing: {df[col].unique()}")
    no_labels = df[emotion_cols].sum(axis=1) == 0
    logger.info(f"Samples with no labels before filtering: {no_labels.sum()}")
    print(f"Samples with no labels before filtering: {no_labels.sum()}")
    df = df[~no_labels].reset_index(drop=True)
    logger.info(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    print(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    return df

# Load dataset
def load_dataset(data_paths, results_dir):
    df = pd.read_excel(data_paths['dataset'])
    # Split dataset into train (80%), validation (10%), test (10%)
    train_df, temp_df = train_test_split(df, train_size=0.8, random_state=CONFIG['seed'])
    val_df, test_df = train_test_split(temp_df, train_size=0.5, random_state=CONFIG['seed'])
    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)
    train_df.to_csv(os.path.join(results_dir, 'train_split.csv'), index=False)
    val_df.to_csv(os.path.join(results_dir, 'dev_split.csv'), index=False)
    test_df.to_csv(os.path.join(results_dir, 'test_split.csv'), index=False)
    return train_df, val_df, test_df

# Adaptive Lambda Network
class LambdaNet(nn.Module):
    def __init__(self, input_dim=2):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 2),
            nn.Sigmoid()
        )

    def forward(self, x):
        lambdas = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        return lambdas

# Adaptive GraphSAGE Layer
class AdaptiveGraphSAGELayer(nn.Module):
    def __init__(self, in_features, out_features, max_neighbors=10):
        super().__init__()
        self.fc_self = nn.Linear(in_features, out_features)
        self.fc_neigh = nn.Linear(in_features, out_features)
        self.norm = nn.LayerNorm(out_features)
        self.max_neighbors = max_neighbors
        self.aggregator_weights = nn.Parameter(torch.ones(3) / 3)

    def forward(self, h, adj, num_neighbors):
        batch_size = h.size(0)
        _, topk_indices = torch.topk(adj, min(num_neighbors, adj.size(1)), dim=1)
        h_neigh_mean = torch.zeros_like(h)
        h_neigh_max = torch.zeros_like(h)
        h_neigh_attn = torch.zeros_like(h)

        for i in range(batch_size):
            neigh_indices = topk_indices[i]
            if neigh_indices.numel() > 0:
                h_neigh_mean[i] = torch.mean(h[neigh_indices], dim=0)
                h_neigh_max[i] = torch.max(h[neigh_indices], dim=0)[0]
                attn_scores = F.softmax(torch.matmul(h[neigh_indices], h[i].unsqueeze(-1)), dim=0)
                h_neigh_attn[i] = torch.sum(h[neigh_indices] * attn_scores, dim=0)

        aggregator_weights = F.softmax(self.aggregator_weights, dim=0)
        h_neigh = (aggregator_weights[0] * h_neigh_mean +
                   aggregator_weights[1] * h_neigh_max +
                   aggregator_weights[2] * h_neigh_attn)

        h_self = self.fc_self(h)
        h_neigh = self.fc_neigh(h_neigh)
        h_prime = h_self + h_neigh
        h_prime = self.norm(F.relu(h_prime))
        return h_prime

# Adaptive Loss Weight Network
class LossWeightNet(nn.Module):
    def __init__(self, input_dim=1):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 3),
            nn.Sigmoid()
        )
        self.prev_weights = None
        self.ema_alpha = CONFIG['ema_alpha']

    def forward(self, x):
        weights = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        if self.prev_weights is not None:
            weights = self.ema_alpha * self.prev_weights + (1 - self.ema_alpha) * weights
        self.prev_weights = weights.detach()
        return weights

# GTHL-Emo Model
class GTHLEmo(nn.Module):
    def __init__(self, num_emotions, embedding_dim=768, gcn_hidden_dim=768, gcn_layers=1):
        super().__init__()
        self.num_emotions = num_emotions
        self.embedding_dim = embedding_dim
        self.gcn_layers = gcn_layers

        model_name = "UBC-NLP/MARBERT"
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True, cache_dir='./cache')
            self.transformer = AutoModel.from_pretrained(model_name, cache_dir='./cache')
        except Exception as e:
            logger.error(f"Failed to download {model_name}: {e}")
            raise RuntimeError(f"Ensure network connectivity or pre-download {model_name} to ./cache")

        lora_config = LoraConfig(
            r=CONFIG['lora_rank'],
            lora_alpha=16,
            target_modules=["query", "key", "value", "dense"],
            lora_dropout=0.1
        )
        self.transformer = get_peft_model(self.transformer, lora_config)

        self.attention_weight = nn.Parameter(torch.randn(embedding_dim))
        self.attention_bias = nn.Parameter(torch.tensor(0.0))
        self.attention_fc = nn.Linear(embedding_dim, embedding_dim)

        self.gcn_layers_list = nn.ModuleList([
            AdaptiveGraphSAGELayer(embedding_dim if i == 0 else gcn_hidden_dim, gcn_hidden_dim, CONFIG['graphsage_neighbors'])
            for i in range(gcn_layers)
        ])

        self.fusion_fc = nn.Linear(embedding_dim * 2, embedding_dim)
        self.fusion_norm = nn.LayerNorm(embedding_dim)

        self.label_embeddings = nn.Parameter(torch.randn(num_emotions, embedding_dim))
        self.label_transformer_layers = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=embedding_dim,
                nhead=CONFIG['label_transformer_heads'],
                dim_feedforward=512,
                dropout=0.1,
                batch_first=True
            ) for _ in range(CONFIG['label_transformer_layers'])
        ])

        self.classifier = nn.Linear(embedding_dim, num_emotions)
        self.classifier_bias = nn.Parameter(torch.zeros(num_emotions))

        self.lambda_net = LambdaNet().to(device)
        self.loss_weight_net = LossWeightNet().to(device)
        self.emoji_cooccurrence = {}
        self.emoji_embeddings = nn.ParameterDict()

        self.loss_fn = GTHLEmoLoss(
            focal_lambda=CONFIG['focal_lambda'],
            graph_lambda=CONFIG['graph_lambda'],
            ranking_lambda=CONFIG['ranking_lambda'],
            num_emotions=num_emotions,
            similarity_threshold=CONFIG['similarity_threshold']
        )

        self.to(device)

    def update_emoji_embeddings(self, texts, labels):
        for text, label in zip(texts, labels):
            emojis = re.findall(r'\U0001F600-\U0001F64F', text)
            for e in emojis:
                if e not in self.emoji_cooccurrence:
                    self.emoji_cooccurrence[e] = np.zeros(self.num_emotions)
                for i, val in enumerate(label):
                    if val == 1:
                        self.emoji_cooccurrence[e][i] += 1
        for e in self.emoji_cooccurrence:
            if e not in self.emoji_embeddings:
                embedding = torch.randn(self.embedding_dim, device=device, requires_grad=True)
                self.emoji_embeddings[e] = nn.Parameter(embedding)
            else:
                counts = torch.tensor(self.emoji_cooccurrence[e], dtype=torch.float32, device=device)
                norm_counts = counts / (counts.sum() + 1e-7)
                emotion_emb = self.label_embeddings @ norm_counts
                self.emoji_embeddings[e].data = 0.9 * self.emoji_embeddings[e].data + 0.1 * emotion_emb

    def preprocess_with_emoji(self, text):
        if not isinstance(text, str) or not text.strip():
            return "[EMPTY]"
        for emoji_char, embedding in self.emoji_embeddings.items():
            if emoji_char in text:
                emotion_idx = torch.topk(torch.matmul(F.normalize(embedding, dim=0), F.normalize(self.label_embeddings, dim=1).t()), 1).indices.item()
                emotion_word = CONFIG['emotion_labels'][emotion_idx]
                text = text.replace(emoji_char, f" {emotion_word} ")
        return preprocess_text(text)

    def prepare_inputs(self, texts):
        valid_texts = [self.preprocess_with_emoji(t) for t in texts if isinstance(t, str) and t.strip() and self.preprocess_with_emoji(t) != "[EMPTY]"]
        if not valid_texts:
            logger.warning("No valid texts in batch; returning dummy input")
            return {'input_ids': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device)}
        try:
            enc = self.tokenizer(
                valid_texts,
                padding='max_length',
                truncation=True,
                max_length=CONFIG['max_length'],
                return_tensors='pt',
                return_attention_mask=True
            )
            input_ids = enc['input_ids']
            attention_mask = enc['attention_mask']
            return {'input_ids': input_ids.to(device), 'attention_mask': attention_mask.to(device)}
        except Exception as e:
            logger.error(f"Tokenization failed: {e}")
            return {'input_ids': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device)}

    def compute_adjacency(self, h_span, labels=None):
        batch_size = h_span.size(0)
        if batch_size <= 1:
            return torch.eye(batch_size, device=h_span.device), 1.0
        h_span_norm = F.normalize(h_span, dim=1)
        cosine_sim = torch.matmul(h_span_norm, h_span_norm.t()).cpu().detach().numpy()
        similarity_threshold = np.percentile(cosine_sim.flatten(), 75) if cosine_sim.size > 1 else CONFIG['similarity_threshold']

        if labels is None:
            sim = cosine_sim
        else:
            labels_np = labels.cpu().numpy()
            jaccard_sim = np.zeros((batch_size, batch_size))
            for i in range(batch_size):
                for j in range(batch_size):
                    jaccard_sim[i, j] = jaccard_score(labels_np[i], labels_np[j], zero_division=0)
            mean_cosine = np.mean(cosine_sim)
            label_entropy = entropy(labels_np.sum(axis=0) / (labels_np.sum() + 1e-7))
            lambda_inputs = torch.tensor([mean_cosine, label_entropy], dtype=torch.float32, device=h_span.device).unsqueeze(0)
            lambda1, lambda2 = self.lambda_net(lambda_inputs)[0]
            sim = lambda1.item() * jaccard_sim + lambda2.item() * cosine_sim

        adj = sparse.csr_matrix((sim > similarity_threshold).astype(float))
        adj = adj + sparse.eye(batch_size, format='csr')
        degree = np.array(adj.sum(axis=1)).flatten()
        degree_inv_sqrt = sparse.diags(1.0 / np.sqrt(degree + 1e-7))
        adj_norm = degree_inv_sqrt @ adj @ degree_inv_sqrt
        return torch.tensor(adj_norm.toarray(), dtype=torch.float32, device=h_span.device), degree.mean()

    def forward(self, texts, labels=None, training=True, return_spans=False):
        if training and labels is not None:
            self.update_emoji_embeddings(texts, labels.cpu().numpy())
        inputs = self.prepare_inputs(texts)
        outputs = self.transformer(input_ids=inputs['input_ids'], attention_mask=inputs['attention_mask'])
        hidden_states = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']

        scores = torch.matmul(hidden_states, self.attention_weight) + self.attention_bias
        scores = torch.clamp(scores, -1e4, 1e4)
        scores = scores.masked_fill(attention_mask == 0, -1e4)
        alpha = F.softmax(scores, dim=1)
        h_span = torch.sum(hidden_states * alpha.unsqueeze(-1), dim=1)
        h_span = self.attention_fc(h_span)

        adj, avg_degree = self.compute_adjacency(h_span, labels)
        num_neighbors = max(2, min(CONFIG['graphsage_neighbors'], int(avg_degree)))

        h_graph = h_span
        for layer in self.gcn_layers_list:
            h_graph = layer(h_graph, adj, num_neighbors)

        h_fused = torch.cat([h_span, h_graph], dim=-1)
        h_fused = self.fusion_norm(F.relu(self.fusion_fc(h_fused)))

        label_emb = self.label_embeddings.unsqueeze(1)
        for layer in self.label_transformer_layers:
            label_emb = layer(label_emb)
        label_emb = label_emb.squeeze(1)

        logits = self.classifier(h_fused) + self.classifier_bias
        y_hat = torch.sigmoid(logits)

        if return_spans:
            span_scores = torch.einsum('bld,cd->blc', hidden_states, label_emb)
            span_attn = F.softmax(span_scores.masked_fill(attention_mask.unsqueeze(-1) == 0, -1e4), dim=1)
            return y_hat, span_attn, inputs['input_ids']
        return y_hat

# Adaptive Loss Function
class GTHLEmoLoss(nn.Module):
    def __init__(self, focal_lambda=0.1, graph_lambda=0.1, ranking_lambda=0.1, num_emotions=10, similarity_threshold=0.5):
        super().__init__()
        self.base_focal_lambda = focal_lambda
        self.base_graph_lambda = graph_lambda
        self.base_ranking_lambda = ranking_lambda
        self.num_emotions = num_emotions
        self.similarity_threshold = similarity_threshold
        self.margin = 0.5

    def bce_loss(self, y_pred, y_true):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        return -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()

    def focal_loss(self, y_pred, y_true, alpha=0.25, gamma=2.0):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        pt = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        focal = -alpha * (1 - pt) ** gamma * torch.log(pt)
        return focal.mean()

    def ranking_loss(self, y_pred, y_true):
        batch_size, num_labels = y_pred.size()
        loss = torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        for i in range(batch_size):
            pos_indices = y_true[i].nonzero(as_tuple=True)[0]
            neg_indices = (1 - y_true[i]).nonzero(as_tuple=True)[0]
            if len(pos_indices) == 0 or len(neg_indices) == 0:
                continue
            pos_scores = y_pred[i, pos_indices]
            neg_scores = y_pred[i, neg_indices]
            diff = pos_scores.unsqueeze(1) - neg_scores.unsqueeze(0)
            loss = loss + F.relu(self.margin - diff).mean()
        return loss / (batch_size + 1e-7)

    def graph_kl_loss(self, label_emb, y_true):
        A = torch.matmul(y_true.t(), y_true) / (y_true.size(0) + 1e-7)
        L_norm = F.normalize(label_emb, dim=1)
        Q = torch.matmul(L_norm, L_norm.t())
        A = F.softmax(A, dim=1)
        Q = F.softmax(Q, dim=1)
        kl = F.kl_div(Q.log(), A, reduction='batchmean')
        return torch.clamp(kl, 0, 10)

    def compute_adaptive_focal_params(self, y_true):
        class_counts = y_true.sum(dim=0).cpu().numpy()
        total = y_true.sum().item() + 1e-7
        class_freq = class_counts / total
        alpha = 1.0 - class_freq / (class_freq.max() + 1e-7)
        alpha = np.clip(alpha, 0.1, 0.9)
        gamma = 2.0 + 2.0 * entropy(class_freq)
        return alpha.mean(), min(gamma, 4.0)

    def forward(self, y_pred, y_true, label_emb=None, loss_weight_net=None, jaccard_score=None):
        bce = self.bce_loss(y_pred, y_true)
        alpha, gamma = self.compute_adaptive_focal_params(y_true)
        focal = self.focal_loss(y_pred, y_true, alpha, gamma) if self.base_focal_lambda is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        ranking = self.ranking_loss(y_pred, y_true) if self.base_ranking_lambda is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        graph_kl = self.graph_kl_loss(label_emb, y_true) if label_emb is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)

        if loss_weight_net is not None and jaccard_score is not None:
            weights = loss_weight_net(torch.tensor([jaccard_score], dtype=torch.float32, device=y_pred.device).unsqueeze(0))
            focal_lambda, graph_lambda, ranking_lambda = weights[0]
        else:
            focal_lambda = self.base_focal_lambda
            graph_lambda = self.base_graph_lambda
            ranking_lambda = self.base_ranking_lambda

        total_loss = bce + focal_lambda * focal + ranking_lambda * ranking + graph_lambda * graph_kl
        return total_loss, bce, focal, ranking, graph_kl

# Training Function
def train_model(model, train_texts, val_texts, train_labels, val_labels, weights_file):
    print("Training model")
    logger.info("Training model")
    optimizer = optim.AdamW(model.parameters(), lr=CONFIG['learning_rate'], weight_decay=CONFIG['weight_decay'])
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=3)
    scaler = GradScaler()
    best_val_jaccard = 0
    patience_counter = 0
    history = {
        'loss': [], 'val_loss': [],
        'bce_loss': [], 'val_bce_loss': [],
        'focal_loss': [], 'val_focal_loss': [],
        'ranking_loss': [], 'val_ranking_loss': [],
        'graph_kl_loss': [], 'val_graph_kl_loss': [],
        'jaccard': [], 'val_jaccard': []
    }

    train_batches = (len(train_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    val_batches = (len(val_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']

    for epoch in range(CONFIG['epochs']):
        model.train()
        train_loss = train_bce_loss = train_focal_loss = train_ranking_loss = train_graph_kl_loss = train_jaccard = 0
        valid_train_batches = 0

        train_pbar = tqdm(range(train_batches), desc=f"Epoch {epoch+1} Training (Jaccard: 0.0000)", leave=True)
        for i in train_pbar:
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(train_texts))
            batch_texts = train_texts[start:end]
            batch_labels = train_labels[start:end]

            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                logger.warning(f"Skipping batch {i+1}: empty texts or no labels")
                continue

            batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

            optimizer.zero_grad()
            with autocast(device_type=device_type):
                try:
                    y_hat = model(batch_texts, labels=batch_labels)
                    loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                        y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                        train_jaccard / max(valid_train_batches, 1)
                    )
                except Exception as e:
                    logger.warning(f"Error in batch {i+1}: {e}")
                    continue

            if torch.isnan(loss) or torch.isinf(loss):
                logger.warning(f"Invalid loss detected in batch {i+1}: {loss.item()}")
                print(f"Invalid loss detected in batch {i+1}: {loss.item()}")
                continue

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
            scaler.step(optimizer)
            scaler.update()

            preds = (y_hat.detach() > 0.5).float()
            batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

            train_loss += loss.item()
            train_bce_loss += bce_loss.item()
            train_focal_loss += focal_loss.item()
            train_ranking_loss += ranking_loss.item()
            train_graph_kl_loss += graph_kl_loss.item()
            train_jaccard += batch_jaccard
            valid_train_batches += 1

            train_pbar.set_postfix({'Jaccard': f"{train_jaccard / valid_train_batches:.4f}"})
            train_pbar.set_description(f"Epoch {epoch+1} Training (Jaccard: {train_jaccard / valid_train_batches:.4f})")

            torch.cuda.empty_cache()

        if valid_train_batches > 0:
            train_loss /= valid_train_batches
            train_bce_loss /= valid_train_batches
            train_focal_loss /= valid_train_batches
            train_ranking_loss /= valid_train_batches
            train_graph_kl_loss /= valid_train_batches
            train_jaccard /= valid_train_batches

        # Validation
        model.eval()
        val_loss = val_bce_loss = val_focal_loss = val_ranking_loss = val_graph_kl_loss = val_jaccard = 0
        valid_val_batches = 0

        val_pbar = tqdm(range(val_batches), desc=f"Epoch {epoch+1} Validation (Jaccard: 0.0000)", leave=True)
        with torch.no_grad():
            for i in val_pbar:
                start = i * CONFIG['batch_size']
                end = min(start + CONFIG['batch_size'], len(val_texts))
                batch_texts = val_texts[start:end]
                batch_labels = val_labels[start:end]

                if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                    continue

                batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

                with autocast(device_type=device_type):
                    try:
                        y_hat = model(batch_texts, labels=batch_labels)
                        loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                            y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                            val_jaccard / max(valid_val_batches, 1)
                        )
                    except Exception as e:
                        logger.warning(f"Error in validation batch {i+1}: {e}")
                        continue

                preds = (y_hat.detach() > 0.5).float()
                batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

                val_loss += loss.item()
                val_bce_loss += bce_loss.item()
                val_focal_loss += focal_loss.item()
                val_ranking_loss += ranking_loss.item()
                val_graph_kl_loss += graph_kl_loss.item()
                val_jaccard += batch_jaccard
                valid_val_batches += 1

                val_pbar.set_postfix({'Jaccard': f"{val_jaccard / valid_val_batches:.4f}"})
                val_pbar.set_description(f"Epoch {epoch+1} Validation (Jaccard: {val_jaccard / valid_val_batches:.4f})")

                torch.cuda.empty_cache()

        if valid_val_batches > 0:
            val_loss /= valid_val_batches
            val_bce_loss /= valid_val_batches
            val_focal_loss /= valid_val_batches
            val_ranking_loss /= valid_val_batches
            val_graph_kl_loss /= valid_val_batches
            val_jaccard /= valid_val_batches

        # Log and store history
        print(f"\nEpoch {epoch+1} Summary:")
        print(f"Train Loss: {train_loss:.4f} (BCE: {train_bce_loss:.4f}, Focal: {train_focal_loss:.4f}, Ranking: {train_ranking_loss:.4f}, Graph KL: {train_graph_kl_loss:.4f})")
        print(f"Train Jaccard: {train_jaccard:.4f}")
        print(f"Val Loss: {val_loss:.4f} (BCE: {val_bce_loss:.4f}, Focal: {val_focal_loss:.4f}, Ranking: {val_ranking_loss:.4f}, Graph KL: {val_graph_kl_loss:.4f})")
        print(f"Val Jaccard: {val_jaccard:.4f}")

        history['loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['bce_loss'].append(train_bce_loss)
        history['val_bce_loss'].append(val_bce_loss)
        history['focal_loss'].append(train_focal_loss)
        history['val_focal_loss'].append(val_focal_loss)
        history['ranking_loss'].append(train_ranking_loss)
        history['val_ranking_loss'].append(val_ranking_loss)
        history['graph_kl_loss'].append(train_graph_kl_loss)
        history['val_graph_kl_loss'].append(val_graph_kl_loss)
        history['jaccard'].append(train_jaccard)
        history['val_jaccard'].append(val_jaccard)

        scheduler.step()

        if val_jaccard > best_val_jaccard:
            best_val_jaccard = val_jaccard
            if check_disk_space(CONFIG['results_dir']):
                torch.save(model.state_dict(), weights_file)
                print(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
                logger.info(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= CONFIG['patience']:
                print(f"Early stopping at epoch {epoch+1}")
                logger.info(f"Early stopping at epoch {epoch+1}")
                break

        check_disk_space(CONFIG['results_dir'])

    if os.path.exists(weights_file):
        model.load_state_dict(torch.load(weights_file))
        print(f"Loaded best model from {weights_file}")
        logger.info(f"Loaded best model from {weights_file}")
    else:
        print(f"No saved model found at {weights_file}")
        logger.warning(f"No saved model found at {weights_file}")

    pd.DataFrame(history).to_csv(os.path.join(CONFIG['results_dir'], 'training_history.csv'), index=False)
    return model, history

# Evaluation
def evaluate_classifier(model, texts, labels, split='test'):
    logger.info(f"Evaluating classifier on {split} split")
    print(f"Evaluating classifier on {split} split")
    model.eval()
    num_batches = (len(texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    preds_proba = []
    span_attns = []
    input_ids_list = []

    with torch.no_grad():
        for i in tqdm(range(num_batches), desc=f"Evaluating {split}", leave=False):
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(texts))
            batch_texts = texts[start:end]
            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                continue
            with autocast(device_type=device_type):
                try:
                    y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                    preds_proba.append(y_hat.cpu().float())
                    span_attns.append(span_attn.cpu())
                    input_ids_list.append(input_ids.cpu())
                except Exception as e:
                    logger.warning(f"Error in evaluation batch {i+1}: {e}")
                    continue
            torch.cuda.empty_cache()

    if not preds_proba:
        logger.warning(f"No valid predictions for {split} split")
        return {}, {}, np.zeros_like(labels), {}, {}

    preds_proba = torch.cat(preds_proba, dim=0).numpy()
    span_attn = torch.cat(span_attns, dim=0)
    input_ids = torch.cat(input_ids_list, dim=0)
    labels = np.array(labels)

    thresholds = np.arange(0.1, 0.5, 0.01)
    best_thresholds = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        best_jaccard = 0
        best_t = 0.5
        for t in thresholds:
            preds = (preds_proba[:, i] >= t).astype(int)
            j = jaccard_score(labels[:, i], preds, zero_division=0)
            if j > best_jaccard:
                best_jaccard = j
                best_t = t
        best_thresholds[label] = best_t

    preds = np.zeros_like(preds_proba)
    for i, label in enumerate(CONFIG['emotion_labels']):
        preds[:, i] = (preds_proba[:, i] >= best_thresholds[label]).astype(int)

    ap_scores = []
    no_positive_labels = []
    for i, label in enumerate(CONFIG['emotion_labels']):
        positive_count = np.sum(labels[:, i])
        logger.info(f"{split} set - {label}: {positive_count} positive samples")
        print(f"{split} set - {label}: {positive_count} positive samples")
        if positive_count == 0:
            logger.warning(f"No positive samples for label {label} in {split} set; skipping Average Precision")
            no_positive_labels.append(label)
            continue
        ap = average_precision_score(labels[:, i], preds_proba[:, i])
        if not np.isnan(ap):
            ap_scores.append(ap)

    metrics = {
        'jaccard': jaccard_score(labels, preds, average='samples', zero_division=0),
        'hamming_loss': hamming_loss(labels, preds),
        'precision': precision_score(labels, preds, average='samples', zero_division=0),
        'recall': recall_score(labels, preds, average='samples', zero_division=0),
        'f1': f1_score(labels, preds, average='samples', zero_division=0),
        'micro_precision': precision_score(labels, preds, average='micro', zero_division=0),
        'micro_recall': recall_score(labels, preds, average='micro', zero_division=0),
        'micro_f1': f1_score(labels, preds, average='micro', zero_division=0),
        'macro_precision': precision_score(labels, preds, average='macro', zero_division=0),
        'macro_recall': recall_score(labels, preds, average='macro', zero_division=0),
        'macro_f1': f1_score(labels, preds, average='macro', zero_division=0),
        'mean_average_precision': np.mean(ap_scores) if ap_scores else np.nan
    }

    class_metrics = {}
    confusion_matrices = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        class_metrics[label] = {
            'precision': precision_score(labels[:, i], preds[:, i], zero_division=0),
            'recall': recall_score(labels[:, i], preds[:, i], zero_division=0),
            'f1': f1_score(labels[:, i], preds[:, i], zero_division=0),
            'average_precision': average_precision_score(labels[:, i], preds_proba[:, i]) if np.sum(labels[:, i]) > 0 else np.nan,
            'threshold': best_thresholds[label]
        }
        cm = confusion_matrix(labels[:, i], preds[:, i])
        confusion_matrices[label] = cm
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
        plt.title(f'Confusion Matrix for {label}')
        plt.xlabel('Predicted')
        plt.ylabel('True')
        plt.savefig(os.path.join(CONFIG['results_dir'], f'confusion_matrix_{label}_{split}.png'), bbox_inches='tight')
        plt.close()

    for i in range(min(5, len(texts))):
        if all(t == "[EMPTY]" for t in texts[i:i+1]):
            continue
        for j, emotion in enumerate(CONFIG['emotion_labels']):
            if preds[i, j] == 1:
                attn_scores = span_attn[i, :, j]  # Keep as tensor
                valid_length = input_ids[i].ne(model.tokenizer.pad_token_id).sum().item()
                k = min(CONFIG['top_k_spans'], valid_length)
                if k > 0:
                    top_k_idx = torch.topk(attn_scores[:valid_length], k).indices
                    tokens = model.tokenizer.convert_ids_to_tokens(input_ids[i][top_k_idx])
                    tokens = [token.replace('##', '') for token in tokens]
                    # Convert only the selected attention scores to NumPy for plotting
                    attn_scores_np = attn_scores[top_k_idx].cpu().numpy()
                    plt.figure(figsize=(12, 2))
                    sns.heatmap([attn_scores_np], xticklabels=tokens, cmap='Blues', annot=True, fmt='.2f')
                    plt.title(f'Attention Heatmap for {emotion} (Sample {i+1})')
                    plt.xlabel('Tokens')
                    plt.ylabel('Attention')
                    plt.savefig(os.path.join(CONFIG['results_dir'], f'attention_heatmap_sample_{i+1}_{emotion}_{split}.png'), bbox_inches='tight')
                    plt.close()

    return metrics, class_metrics, preds, best_thresholds, confusion_matrices

# Inference
def infer_emotions(model, texts, thresholds, use_mc_dropout=False):
    logger.info("Performing inference")
    print("Performing inference")
    model.eval()
    processed_texts = [model.preprocess_with_emoji(text) for text in texts]
    num_batches = (len(processed_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']

    if use_mc_dropout:
        model.train()
        all_preds_proba = []
        all_span_attns = []
        all_input_ids = []
        for _ in range(CONFIG['mc_dropout_samples']):
            preds_proba = []
            span_attns = []
            input_ids_list = []
            with torch.no_grad():
                for i in range(num_batches):
                    start = i * CONFIG['batch_size']
                    end = min(start + CONFIG['batch_size'], len(processed_texts))
                    batch_texts = processed_texts[start:end]
                    if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                        continue
                    with autocast(device_type=device_type):
                        try:
                            y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                            preds_proba.append(y_hat.cpu().float())
                            span_attns.append(span_attn.cpu())
                            input_ids_list.append(input_ids.cpu())
                        except Exception as e:
                            logger.warning(f"Error in inference batch {i+1}: {e}")
                            continue
                    torch.cuda.empty_cache()
                if preds_proba:
                    all_preds_proba.append(torch.cat(preds_proba, dim=0))
                    all_span_attns.append(torch.cat(span_attns, dim=0))
                    all_input_ids.append(torch.cat(input_ids_list, dim=0))
        if not all_preds_proba:
            logger.warning("No valid predictions in MC dropout; returning empty results")
            return [{'text': t, 'processed_text': pt, 'emotions': ['none'], 'probabilities': {}, 'uncertainty': {}, 'attributed_spans': {}} for t, pt in zip(texts, processed_texts)]
        preds_proba = torch.stack(all_preds_proba).mean(dim=0).numpy()
        preds_std = torch.stack(all_preds_proba).std(dim=0).numpy()
        span_attn = torch.stack(all_span_attns).mean(dim=0)
        input_ids = torch.stack(all_input_ids).mean(dim=0).long()
    else:
        preds_proba = []
        span_attns = []
        input_ids_list = []
        with torch.no_grad():
            for i in range(num_batches):
                start = i * CONFIG['batch_size']
                end = min(start + CONFIG['batch_size'], len(processed_texts))
                batch_texts = processed_texts[start:end]
                if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                    continue
                with autocast(device_type=device_type):
                    try:
                        y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                        preds_proba.append(y_hat.cpu().float())
                        span_attns.append(span_attn.cpu())
                        input_ids_list.append(input_ids.cpu())
                    except Exception as e:
                        logger.warning(f"Error in inference batch {i+1}: {e}")
                        continue
                torch.cuda.empty_cache()
        if not preds_proba:
            logger.warning("No valid predictions; returning empty results")
            return [{'text': t, 'processed_text': pt, 'emotions': ['none'], 'probabilities': {}, 'uncertainty': {}, 'attributed_spans': {}} for t, pt in zip(texts, processed_texts)]
        preds_proba = torch.cat(preds_proba, dim=0).numpy()
        span_attn = torch.cat(span_attns, dim=0)
        input_ids = torch.cat(input_ids_list, dim=0)
        preds_std = np.zeros_like(preds_proba)

    preds = np.zeros_like(preds_proba)
    for i, label in enumerate(CONFIG['emotion_labels']):
        preds[:, i] = (preds_proba[:, i] >= thresholds[label]).astype(int)

    results = []
    for i, pred in enumerate(preds):
        emotions = [CONFIG['emotion_labels'][j] for j, val in enumerate(pred) if val == 1]
        attributed_spans = {}
        valid_length = input_ids[i].ne(model.tokenizer.pad_token_id).sum().item()
        for j, emotion in enumerate(CONFIG['emotion_labels']):
            if pred[j] == 1 and valid_length > 0:
                attn_scores = span_attn[i, :, j]  # Keep as tensor
                k = min(CONFIG['top_k_spans'], valid_length)
                if k > 0:
                    top_k_idx = torch.topk(attn_scores[:valid_length], k).indices
                    tokens = model.tokenizer.convert_ids_to_tokens(input_ids[i][top_k_idx])
                    tokens = [token.replace('##', '') for token in tokens]
                    attributed_spans[emotion] = tokens
        results.append({
            'text': texts[i],
            'processed_text': processed_texts[i],
            'emotions': emotions if emotions else ['none'],
            'probabilities': {CONFIG['emotion_labels'][j]: float(prob) for j, prob in enumerate(preds_proba[i])},
            'uncertainty': {CONFIG['emotion_labels'][j]: float(std) for j, std in enumerate(preds_std[i])} if use_mc_dropout else {},
            'attributed_spans': attributed_spans
        })
    return results

# Generate Test Predictions
def generate_test_predictions(model, test_texts, thresholds, output_file):
    logger.info("Generating test set predictions")
    print("Generating test set predictions")
    predictions = infer_emotions(model, test_texts, thresholds, use_mc_dropout=False)
    submission = pd.DataFrame({
        'ID': [f'sample_{i}' for i, text in enumerate(test_texts)],
        'content': test_texts
    })
    for label in CONFIG['emotion_labels']:
        submission[label] = [1 if pred['probabilities'][label] >= thresholds[label] else 0 for pred in predictions]
    submission.to_csv(output_file, index=False, sep='\t')
    logger.info(f"Saved test predictions to {output_file}")
    print(f"Saved test predictions to {output_file}")
    return submission

# Main Execution
if __name__ == "__main__":
    print("Starting GTHL-Emo model training with MARBERT on ExaAEC dataset")
    logger.info("Starting GTHL-Emo model training with MARBERT on ExaAEC dataset")

    cleanup_old_models(CONFIG['results_dir'])
    train_df, val_df, test_df = load_dataset(CONFIG['data_paths'], CONFIG['results_dir'])
    train_processed = preprocess_data(train_df)
    val_processed = preprocess_data(val_df)
    test_processed = preprocess_data(test_df)
    train_labels = train_processed[CONFIG['emotion_labels']].values
    val_labels = val_processed[CONFIG['emotion_labels']].values
    test_labels = test_processed[CONFIG['emotion_labels']].values

    # Log test set positive samples
    for col in CONFIG['emotion_labels']:
        positive_count = np.sum(test_labels[:, CONFIG['emotion_labels'].index(col)])
        logger.info(f"Test set - {col}: {positive_count} positive samples")
        print(f"Test set - {col}: {positive_count} positive samples")

    train_processed.to_csv(os.path.join(CONFIG['results_dir'], 'train_processed.csv'), index=False)
    val_processed.to_csv(os.path.join(CONFIG['results_dir'], 'val_processed.csv'), index=False)
    test_processed.to_csv(os.path.join(CONFIG['results_dir'], 'test_processed.csv'), index=False)

    print("\nDataset Sizes:")
    print(f"Training set: {len(train_processed)} samples")
    print(f"Validation set: {len(val_processed)} samples")
    print(f"Test set: {len(test_processed)} samples")
    logger.info(f"Training set size: {len(train_processed)}")
    logger.info(f"Validation set size: {len(val_processed)}")
    logger.info(f"Test set size: {len(test_processed)}")

    print("\nTraining model...")
    model = GTHLEmo(
        num_emotions=len(CONFIG['emotion_labels']),
        embedding_dim=CONFIG['embedding_dim'],
        gcn_hidden_dim=CONFIG['gcn_hidden_dim'],
        gcn_layers=CONFIG['gcn_layers']
    )
    weights_file = os.path.join(CONFIG['results_dir'], 'best_model.pth')
    model, history = train_model(
        model,
        train_processed['content'].tolist(),
        val_processed['content'].tolist(),
        train_labels,
        val_labels,
        weights_file
    )

    val_metrics, val_class_metrics, val_preds, best_thresholds, val_confusion_matrices = evaluate_classifier(
        model, val_processed['content'].tolist(), val_labels, split='val'
    )

    print("\nEvaluating on test set...")
    test_metrics, test_class_metrics, test_preds, test_thresholds, test_confusion_matrices = evaluate_classifier(
        model, test_processed['content'].tolist(), test_labels, split='test'
    )
    print("\nTest Set Evaluation Results:")
    print(f"Test Jaccard Score: {test_metrics['jaccard']:.4f}")
    print(f"Test Hamming Loss: {test_metrics['hamming_loss']:.4f}")
    print(f"Test Mean Average Precision: {test_metrics['mean_average_precision']:.4f}")
    print("\nOverall Metrics:")
    for metric_name, value in test_metrics.items():
        print(f"{metric_name}: {value:.4f}")
    print("\nClass-wise Metrics:")
    for emotion, scores in test_class_metrics.items():
        print(f"{emotion}:")
        print(f"  Precision: {scores['precision']:.4f}")
        print(f"  Recall: {scores['recall']:.4f}")
        print(f"  F1: {scores['f1']:.4f}")
        print(f"  Average Precision: {scores['average_precision']:.4f}")
        print(f"  Threshold: {scores['threshold']:.4f}")

    plt.figure(figsize=(12, 8))
    plt.subplot(2, 2, 1)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], label='Validation Loss')
    plt.title('Total Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 2)
    plt.plot(history['bce_loss'], label='Train BCE Loss')
    plt.plot(history['val_bce_loss'], label='Validation BCE Loss')
    plt.title('BCE Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 3)
    plt.plot(history['focal_loss'], label='Train Focal Loss')
    plt.plot(history['val_focal_loss'], label='Validation Focal Loss')
    plt.title('Focal Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 4)
    plt.plot(history['jaccard'], label='Train Jaccard')
    plt.plot(history['val_jaccard'], label='Validation Jaccard')
    plt.title('Jaccard Score')
    plt.xlabel('Epoch')
    plt.ylabel('Jaccard')
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(CONFIG['results_dir'], 'training_history.png'))
    plt.close()







"""# Task
Summarize the reported results obtained from the dataset evaluation.

## Extract Overall Metrics

### Subtask:
Extract the overall evaluation metrics (Jaccard Score, Hamming Loss, Mean Average Precision, etc.) from the standard output.

**Reasoning**:
To extract the overall evaluation metrics from the `standard_output`, I will use string manipulation to locate the relevant section and then parse each metric and its corresponding value.
"""

import re

# The standard_output is available as a global variable in this environment
output = """
Using device: cuda (device_type: cuda)
Starting GTHL-Emo model training with MARBERT on ExaAEC dataset
Dataset columns: ['content', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'acceptance', 'sadness', 'surprise', 'neutral']



anger unique values after preprocessing: [0 1]
anticipation unique values after preprocessing: [0 1]
disgust unique values after preprocessing: [0 1]
fear unique values after preprocessing: [0 1]
joy unique values after preprocessing: [0 1]
love unique values after preprocessing: [1 0]
acceptance unique values after preprocessing: [0 1]
sadness unique values after preprocessing: [1 0]
surprise unique values after preprocessing: [0 1]
neutral unique values after preprocessing: [0 1]
Samples with no labels before filtering: 0
Samples with no labels after filtering: 0
Dataset columns: ['content', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'acceptance', 'sadness', 'surprise', 'neutral']


anger unique values after preprocessing: [0 1]
anticipation unique values after preprocessing: [0 1]
disgust unique values after preprocessing: [0 1]
fear unique values after preprocessing: [0 1]
joy unique values after preprocessing: [0 1]
love unique values after preprocessing: [0 1]
acceptance unique values after preprocessing: [1 0]
sadness unique values after preprocessing: [0 1]
surprise unique values after preprocessing: [0 1]
neutral unique values after preprocessing: [0 1]
Samples with no labels before filtering: 0
Samples with no labels after filtering: 0
Dataset columns: ['content', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'acceptance', 'sadness', 'surprise', 'neutral']


anger unique values after preprocessing: [0 1]
anticipation unique values after preprocessing: [0 1]
disgust unique values after preprocessing: [0 1]
fear unique values after preprocessing: [0 1]
joy unique values after preprocessing: [0 1]
love unique values after preprocessing: [0 1]
acceptance unique values after preprocessing: [1 0]
sadness unique values after preprocessing: [0 1]
surprise unique values after preprocessing: [0 1]
neutral unique values after preprocessing: [0 1]
Samples with no labels before filtering: 0
Samples with no labels after filtering: 0
Test set - anger: 143 positive samples
Test set - anticipation: 203 positive samples
Test set - disgust: 433 positive samples
Test set - fear: 49 positive samples
Test set - joy: 102 positive samples
Test set - love: 127 positive samples
Test set - acceptance: 626 positive samples
Test set - sadness: 384 positive samples
Test set - surprise: 211 positive samples
Test set - neutral: 379 positive samples

Dataset Sizes:
Training set: 16017 samples
Validation set: 2004 samples
Test set: 2000 samples

Training model...

Training model




Epoch 1 Summary:
Train Loss: 0.4826 (BCE: 0.2906, Focal: 0.0487, Ranking: 0.2424, Graph KL: 0.0458)
Train Jaccard: 0.4110
Val Loss: 0.3627 (BCE: 0.2293, Focal: 0.0412, Ranking: 0.1601, Graph KL: 0.0443)
Val Jaccard: 0.5767
Free disk space in ./results/: 72.37 GB
Saved best model with Val Jaccard: 0.5767
Free disk space in ./results/: 71.72 GB



Epoch 2 Summary:
Train Loss: 0.3265 (BCE: 0.2100, Focal: 0.0374, Ranking: 0.1412, Graph KL: 0.0434)
Train Jaccard: 0.6076
Val Loss: 0.3134 (BCE: 0.2036, Focal: 0.0399, Ranking: 0.1369, Graph KL: 0.0422)
Val Jaccard: 0.6237
Free disk space in ./results/: 71.72 GB
Saved best model with Val Jaccard: 0.6237
Free disk space in ./results/: 71.72 GB



Epoch 3 Summary:
Train Loss: 0.2899 (BCE: 0.1911, Focal: 0.0341, Ranking: 0.1235, Graph KL: 0.0420)
Train Jaccard: 0.6459
Val Loss: 0.3033 (BCE: 0.1984, Focal: 0.0399, Ranking: 0.1326, Graph KL: 0.0416)
Val Jaccard: 0.6357
Free disk space in ./results/: 71.72 GB
Saved best model with Val Jaccard: 0.6357
Free disk space in ./results/: 71.72 GB



Epoch 4 Summary:
Train Loss: 0.2838 (BCE: 0.1913, Focal: 0.0367, Ranking: 0.1244, Graph KL: 0.0404)
Train Jaccard: 0.6420
Val Loss: 0.2892 (BCE: 0.1974, Focal: 0.0440, Ranking: 0.1303, Graph KL: 0.0390)
Val Jaccard: 0.6340
Free disk space in ./results/: 71.72 GB



Epoch 5 Summary:
Train Loss: 0.2534 (BCE: 0.1777, Focal: 0.0345, Ranking: 0.1132, Graph KL: 0.0381)
Train Jaccard: 0.6697
Val Loss: 0.2726 (BCE: 0.1909, Focal: 0.0442, Ranking: 0.1292, Graph KL: 0.0370)
Val Jaccard: 0.6375
Free disk space in ./results/: 71.72 GB
Saved best model with Val Jaccard: 0.6375
Free disk space in ./results/: 71.72 GB



Epoch 6 Summary:
Train Loss: 0.2300 (BCE: 0.1655, Focal: 0.0319, Ranking: 0.1024, Graph KL: 0.0368)
Train Jaccard: 0.6954
Val Loss: 0.2664 (BCE: 0.1890, Focal: 0.0448, Ranking: 0.1256, Graph KL: 0.0364)
Val Jaccard: 0.6507
Free disk space in ./results/: 71.72 GB
Saved best model with Val Jaccard: 0.6507
Free disk space in ./results/: 71.72 GB



Epoch 7 Summary:
Train Loss: 0.2294 (BCE: 0.1689, Focal: 0.0341, Ranking: 0.1070, Graph KL: 0.0353)
Train Jaccard: 0.6857
Val Loss: 0.2609 (BCE: 0.1927, Focal: 0.0497, Ranking: 0.1310, Graph KL: 0.0339)
Val Jaccard: 0.6419
Free disk space in ./results/: 71.72 GB



Epoch 8 Summary:
Train Loss: 0.2069 (BCE: 0.1586, Focal: 0.0326, Ranking: 0.0986, Graph KL: 0.0332)
Train Jaccard: 0.7064
Val Loss: 0.2505 (BCE: 0.1912, Focal: 0.0500, Ranking: 0.1307, Graph KL: 0.0322)
Val Jaccard: 0.6462
Free disk space in ./results/: 71.72 GB



Epoch 9 Summary:
Train Loss: 0.1873 (BCE: 0.1475, Focal: 0.0288, Ranking: 0.0893, Graph KL: 0.0320)
Train Jaccard: 0.7254
Val Loss: 0.2465 (BCE: 0.1901, Focal: 0.0521, Ranking: 0.1285, Graph KL: 0.0316)
Val Jaccard: 0.6488
Free disk space in ./results/: 71.72 GB



Epoch 10 Summary:
Train Loss: 0.1888 (BCE: 0.1516, Focal: 0.0328, Ranking: 0.0938, Graph KL: 0.0306)
Train Jaccard: 0.7179
Val Loss: 0.2426 (BCE: 0.1944, Focal: 0.0569, Ranking: 0.1322, Graph KL: 0.0293)
Val Jaccard: 0.6453
Free disk space in ./results/: 71.72 GB
Loaded best model from ./results/best_model.pth
Evaluating classifier on val split


val set - anger: 153 positive samples
val set - anticipation: 222 positive samples
val set - disgust: 427 positive samples
val set - fear: 51 positive samples
val set - joy: 116 positive samples
val set - love: 151 positive samples
val set - acceptance: 637 positive samples
val set - sadness: 379 positive samples
val set - surprise: 192 positive samples
val set - neutral: 363 positive samples

Evaluating on test set...
Evaluating classifier on test split


test set - anger: 143 positive samples
test set - anticipation: 203 positive samples
test set - disgust: 433 positive samples
test set - fear: 49 positive samples
test set - joy: 102 positive samples
test set - love: 127 positive samples
test set - acceptance: 626 positive samples
test set - sadness: 384 positive samples
test set - surprise: 211 positive samples
test set - neutral: 379 positive samples

Test Set Evaluation Results:
Test Jaccard Score: 0.6402
Test Hamming Loss: 0.0872
Test Mean Average Precision: 0.7129

Overall Metrics:
jaccard: 0.6402
hamming_loss: 0.0872
precision: 0.6902
recall: 0.7568
f1: 0.6995
micro_precision: 0.6521
micro_recall: 0.7358
micro_f1: 0.6914
macro_precision: 0.6469
macro_recall: 0.7103
macro_f1: 0.6740
mean_average_precision: 0.7129

Class-wise Metrics:
anger:
  Precision: 0.4946
  Recall: 0.6364
  F1: 0.5566
  Average Precision: 0.5281
  Threshold: 0.2800
anticipation:
  Precision: 0.5259
  Recall: 0.6010
  F1: 0.5609
  Average Precision: 0.5847
  Threshold: 0.4400
disgust:
  Precision: 0.6148
  Recall: 0.7667
  F1: 0.6824
  Average Precision: 0.7545
  Threshold: 0.3500
fear:
  Precision: 0.7750
  Recall: 0.6327
  F1: 0.6966
  Average Precision: 0.7238
  Threshold: 0.4700
joy:
  Precision: 0.6804
  Recall: 0.6471
  F1: 0.6633
  Average Precision: 0.6829
  Threshold: 0.3600
love:
  Precision: 0.7248
  Recall: 0.8504
  F1: 0.7826
  Average Precision: 0.8277
  Threshold: 0.3500
acceptance:
  Precision: 0.7597
  Recall: 0.7524
  F1: 0.7560
  Average Precision: 0.8361
  Threshold: 0.3500
sadness:
  Precision: 0.6792
  Recall: 0.7500
  F1: 0.7129
  Average Precision: 0.7647
  Threshold: 0.3800
surprise:
  Precision: 0.5391
  Recall: 0.6540
  F1: 0.5910
  Average Precision: 0.6207
  Threshold: 0.3400
neutral:
  Precision: 0.6754
  Recall: 0.8127
  F1: 0.7377
  Average Precision: 0.8061
  Threshold: 0.3300"""

overall_metrics_start = output.find('Overall Metrics:')
metrics_str = output[overall_metrics_start:].split('Class-wise Metrics:')[0]

overall_metrics = {}
# Regex to capture metric names and their float values
metric_pattern = re.compile(r'(\w+): ([0-9.]+)')

for line in metrics_str.split('\n'):
    match = metric_pattern.search(line)
    if match:
        key = match.group(1)
        value = float(match.group(2))
        overall_metrics[key] = value

print("Extracted Overall Metrics:")
for metric, value in overall_metrics.items():
    print(f"{metric}: {value}")

"""## Extract Class-wise Metrics

### Subtask:
Extract the precision, recall, F1-score, average precision, and threshold for each emotion from the standard output.

**Reasoning**:
To extract the class-wise metrics, I will first locate the 'Class-wise Metrics:' section in the `output` string. Then, I'll use regular expressions to parse each emotion's metrics (Precision, Recall, F1, Average Precision, and Threshold) and store them in a dictionary for structured output.
"""

class_metrics_start = output.find('Class-wise Metrics:')
class_metrics_str = output[class_metrics_start:].split('\n\n')[0] # Split by double newline to get only class metrics section

class_wise_metrics = {}

# Regex to capture emotion name and then the metrics for that emotion
# Using non-greedy matching .*? to stop at the next emotion name or end of section
emotion_pattern = re.compile(r'(\w+):\s+Precision: ([0-9.]+)\s+Recall: ([0-9.]+)\s+F1: ([0-9.]+)\s+Average Precision: ([0-9.]+)\s+Threshold: ([0-9.]+)')

for match in emotion_pattern.finditer(class_metrics_str):
    emotion = match.group(1)
    class_wise_metrics[emotion] = {
        'Precision': float(match.group(2)),
        'Recall': float(match.group(3)),
        'F1': float(match.group(4)),
        'Average Precision': float(match.group(5)),
        'Threshold': float(match.group(6))
    }

print("Extracted Class-wise Metrics:")
for emotion, metrics in class_wise_metrics.items():
    print(f"{emotion}:")
    for metric_name, value in metrics.items():
        print(f"  {metric_name}: {value}")

"""## Summary of Dataset Evaluation Results

### Overall Metrics:

The model achieved the following overall performance on the test set:

- **Jaccard Score**: 0.6402
- **Hamming Loss**: 0.0872
- **Precision**: 0.6902
- **Recall**: 0.7568
- **F1 Score**: 0.6995
- **Micro Precision**: 0.6521
- **Micro Recall**: 0.7358
- **Micro F1 Score**: 0.6914
- **Macro Precision**: 0.6469
- **Macro Recall**: 0.7103
- **Macro F1 Score**: 0.6740
- **Mean Average Precision (mAP)**: 0.7129

### Class-wise Metrics:

The performance for each emotion class is detailed below, including the precision, recall, F1-score, average precision, and the optimal threshold determined for each:

- **anger**:
  - Precision: 0.4946, Recall: 0.6364, F1: 0.5566, Average Precision: 0.5281, Threshold: 0.28
- **anticipation**:
  - Precision: 0.5259, Recall: 0.6010, F1: 0.5609, Average Precision: 0.5847, Threshold: 0.44
- **disgust**:
  - Precision: 0.6148, Recall: 0.7667, F1: 0.6824, Average Precision: 0.7545, Threshold: 0.35
- **fear**:
  - Precision: 0.7750, Recall: 0.6327, F1: 0.6966, Average Precision: 0.7238, Threshold: 0.47
- **joy**:
  - Precision: 0.6804, Recall: 0.6471, F1: 0.6633, Average Precision: 0.6829, Threshold: 0.36
- **love**:
  - Precision: 0.7248, Recall: 0.8504, F1: 0.7826, Average Precision: 0.8277, Threshold: 0.35
- **acceptance**:
  - Precision: 0.7597, Recall: 0.7524, F1: 0.7560, Average Precision: 0.8361, Threshold: 0.35
- **sadness**:
  - Precision: 0.6792, Recall: 0.7500, F1: 0.7129, Average Precision: 0.7647, Threshold: 0.38
- **surprise**:
  - Precision: 0.5391, Recall: 0.6540, F1: 0.5910, Average Precision: 0.6207, Threshold: 0.34
- **neutral**:
  - Precision: 0.6754, Recall: 0.8127, F1: 0.7377, Average Precision: 0.8061, Threshold: 0.33

These results indicate that the model performs reasonably well across various metrics, with `love`, `acceptance`, and `neutral` emotions showing particularly strong performance, while `anger`, `anticipation`, and `surprise` have comparatively lower F1 scores.

## Summary of Dataset Evaluation Results

### Overall Metrics:

The model achieved the following overall performance on the test set:

- **Jaccard Score**: 0.6402
- **Hamming Loss**: 0.0872
- **Precision**: 0.6902
- **Recall**: 0.7568
- **F1 Score**: 0.6995
- **Micro Precision**: 0.6521
- **Micro Recall**: 0.7358
- **Micro F1 Score**: 0.6914
- **Macro Precision**: 0.6469
- **Macro Recall**: 0.7103
- **Macro F1 Score**: 0.6740
- **Mean Average Precision (mAP)**: 0.7129

### Class-wise Metrics:

The performance for each emotion class is detailed below, including the precision, recall, F1-score, average precision, and the optimal threshold determined for each:

- **anger**:
  - Precision: 0.4946, Recall: 0.6364, F1: 0.5566, Average Precision: 0.5281, Threshold: 0.28
- **anticipation**:
  - Precision: 0.5259, Recall: 0.6010, F1: 0.5609, Average Precision: 0.5847, Threshold: 0.44
- **disgust**:
  - Precision: 0.6148, Recall: 0.7667, F1: 0.6824, Average Precision: 0.7545, Threshold: 0.35
- **fear**:
  - Precision: 0.7750, Recall: 0.6327, F1: 0.6966, Average Precision: 0.7238, Threshold: 0.47
- **joy**:
  - Precision: 0.6804, Recall: 0.6471, F1: 0.6633, Average Precision: 0.6829, Threshold: 0.36
- **love**:
  - Precision: 0.7248, Recall: 0.8504, F1: 0.7826, Average Precision: 0.8277, Threshold: 0.35
- **acceptance**:
  - Precision: 0.7597, Recall: 0.7524, F1: 0.7560, Average Precision: 0.8361, Threshold: 0.35
- **sadness**:
  - Precision: 0.6792, Recall: 0.7500, F1: 0.7129, Average Precision: 0.7647, Threshold: 0.38
- **surprise**:
  - Precision: 0.5391, Recall: 0.6540, F1: 0.5910, Average Precision: 0.6207, Threshold: 0.34
- **neutral**:
  - Precision: 0.6754, Recall: 0.8127, F1: 0.7377, Average Precision: 0.8061, Threshold: 0.33

These results indicate that the model performs reasonably well across various metrics, with `love`, `acceptance`, and `neutral` emotions showing particularly strong performance, while `anger`, `anticipation`, and `surprise` have comparatively lower F1 scores.

## Summary of Dataset Evaluation Results

### Overall Metrics:

The model achieved the following overall performance on the test set:

- **Jaccard Score**: 0.6402
- **Hamming Loss**: 0.0872
- **Precision**: 0.6902
- **Recall**: 0.7568
- **F1 Score**: 0.6995
- **Micro Precision**: 0.6521
- **Micro Recall**: 0.7358
- **Micro F1 Score**: 0.6914
- **Macro Precision**: 0.6469
- **Macro Recall**: 0.7103
- **Macro F1 Score**: 0.6740
- **Mean Average Precision (mAP)**: 0.7129

### Class-wise Metrics:

The performance for each emotion class is detailed below, including the precision, recall, F1-score, average precision, and the optimal threshold determined for each:

- **anger**:
  - Precision: 0.4946, Recall: 0.6364, F1: 0.5566, Average Precision: 0.5281, Threshold: 0.28
- **anticipation**:
  - Precision: 0.5259, Recall: 0.6010, F1: 0.5609, Average Precision: 0.5847, Threshold: 0.44
- **disgust**:
  - Precision: 0.6148, Recall: 0.7667, F1: 0.6824, Average Precision: 0.7545, Threshold: 0.35
- **fear**:
  - Precision: 0.7750, Recall: 0.6327, F1: 0.6966, Average Precision: 0.7238, Threshold: 0.47
- **joy**:
  - Precision: 0.6804, Recall: 0.6471, F1: 0.6633, Average Precision: 0.6829, Threshold: 0.36
- **love**:
  - Precision: 0.7248, Recall: 0.8504, F1: 0.7826, Average Precision: 0.8277, Threshold: 0.35
- **acceptance**:
  - Precision: 0.7597, Recall: 0.7524, F1: 0.7560, Average Precision: 0.8361, Threshold: 0.35
- **sadness**:
  - Precision: 0.6792, Recall: 0.7500, F1: 0.7129, Average Precision: 0.7647, Threshold: 0.38
- **surprise**:
  - Precision: 0.5391, Recall: 0.6540, F1: 0.5910, Average Precision: 0.6207, Threshold: 0.34
- **neutral**:
  - Precision: 0.6754, Recall: 0.8127, F1: 0.7377, Average Precision: 0.8061, Threshold: 0.33

These results indicate that the model performs reasonably well across various metrics, with `love`, `acceptance`, and `neutral` emotions showing particularly strong performance, while `anger`, `anticipation`, and `surprise` have comparatively lower F1 scores.

## Present Results

### Subtask:
Present the extracted overall and class-wise metrics in a clear and organized format, including any relevant context or interpretations.

## Evaluation Results Summary

This section summarizes the performance of the GTHL-Emo model on the test set, including overall metrics and a detailed breakdown for each emotion class.

### Overall Model Performance

The model achieved the following overall evaluation metrics on the test set:

- **Jaccard Score**: {{overall_metrics['jaccard']:.4f}}
- **Hamming Loss**: {{overall_metrics['hamming_loss']:.4f}}
- **Mean Average Precision (MAP)**: {{overall_metrics['mean_average_precision']:.4f}}
- **Micro F1-score**: {{overall_metrics['micro_f1']:.4f}}
- **Macro F1-score**: {{overall_metrics['macro_f1']:.4f}}
- **Overall Precision**: {{overall_metrics['precision']:.4f}}
- **Overall Recall**: {{overall_metrics['recall']:.4f}}

The Jaccard Score indicates a moderate level of agreement between predicted and true labels, while the Hamming Loss suggests that on average, a relatively small fraction of labels were incorrectly predicted per sample. The Mean Average Precision provides a good measure of ranking quality across all labels.

### Class-wise Performance Breakdown

Below are the detailed performance metrics for each of the 10 emotion classes:

{% for emotion, metrics in class_wise_metrics.items() %}
**{{ emotion.capitalize() }}**:
-   Precision: {{ metrics['Precision']:.4f }}
-   Recall: {{ metrics['Recall']:.4f }}
-   F1-score: {{ metrics['F1']:.4f }}
-   Average Precision: {{ metrics['Average Precision']:.4f }}
-   Optimal Threshold: {{ metrics['Threshold']:.4f }}
{% endfor %}

### Interpretation and Implications

The model demonstrates varying performance across different emotion classes. Emotions like **Love**, **Acceptance**, and **Fear** show strong performance with high F1-scores and Average Precision values (e.g., Love F1: {{class_wise_metrics['love']['F1']:.4f}}, Acceptance F1: {{class_wise_metrics['acceptance']['F1']:.4f}}, Fear F1: {{class_wise_metrics['fear']['F1']:.4f}}). This suggests the model is highly effective at identifying these emotions, possibly due to clearer linguistic cues or a higher prevalence in the dataset.

Conversely, **Anger**, **Anticipation**, and **Surprise** appear to be more challenging for the model, exhibiting lower F1-scores (e.g., Anger F1: {{class_wise_metrics['anger']['F1']:.4f}}, Anticipation F1: {{class_wise_metrics['anticipation']['F1']:.4f}}, Surprise F1: {{class_wise_metrics['surprise']['F1']:.4f}}). The relatively lower precision for 'anger' and 'anticipation' suggests a higher rate of false positives, while the lower recall might indicate missed true positives. This could be attributed to the nuanced nature of these emotions, less distinct textual indicators, or potential data imbalances.

The thresholds, which vary per emotion, indicate the dynamic nature of classification, where some emotions require a lower confidence score to be activated (e.g., Anger at {{class_wise_metrics['anger']['Threshold']:.2f}}) while others need higher confidence (e.g., Fear at {{class_wise_metrics['fear']['Threshold']:.2f}}).

These results highlight areas for potential improvement, such as focusing on data augmentation or feature engineering for weaker performing classes. Overall, the model provides a solid foundation for emotion detection in Arabic text, with robust performance in several key emotional categories.

## Evaluation Results Summary

This section summarizes the performance of the GTHL-Emo model on the test set, including overall metrics and a detailed breakdown for each emotion class.

### Overall Model Performance

The model achieved the following overall evaluation metrics on the test set:

- **Jaccard Score**: {{overall_metrics['jaccard']:.4f}}
- **Hamming Loss**: {{overall_metrics['hamming_loss']:.4f}}
- **Mean Average Precision (MAP)**: {{overall_metrics['mean_average_precision']:.4f}}
- **Micro F1-score**: {{overall_metrics['micro_f1']:.4f}}
- **Macro F1-score**: {{overall_metrics['macro_f1']:.4f}}
- **Overall Precision**: {{overall_metrics['precision']:.4f}}
- **Overall Recall**: {{overall_metrics['recall']:.4f}}

The Jaccard Score indicates a moderate level of agreement between predicted and true labels, while the Hamming Loss suggests that on average, a relatively small fraction of labels were incorrectly predicted per sample. The Mean Average Precision provides a good measure of ranking quality across all labels.

### Class-wise Performance Breakdown

Below are the detailed performance metrics for each of the 10 emotion classes:

{% for emotion, metrics in class_wise_metrics.items() %}
**{{ emotion.capitalize() }}**:
-   Precision: {{ metrics['Precision']:.4f }}
-   Recall: {{ metrics['Recall']:.4f }}
-   F1-score: {{ metrics['F1']:.4f }}
-   Average Precision: {{ metrics['Average Precision']:.4f }}
-   Optimal Threshold: {{ metrics['Threshold']:.4f }}
{% endfor %}

### Interpretation and Implications

The model demonstrates varying performance across different emotion classes. Emotions like **Love**, **Acceptance**, and **Fear** show strong performance with high F1-scores and Average Precision values (e.g., Love F1: {{class_wise_metrics['love']['F1']:.4f}}, Acceptance F1: {{class_wise_metrics['acceptance']['F1']:.4f}}, Fear F1: {{class_wise_metrics['fear']['F1']:.4f}}). This suggests the model is highly effective at identifying these emotions, possibly due to clearer linguistic cues or a higher prevalence in the dataset.

Conversely, **Anger**, **Anticipation**, and **Surprise** appear to be more challenging for the model, exhibiting lower F1-scores (e.g., Anger F1: {{class_wise_metrics['anger']['F1']:.4f}}, Anticipation F1: {{class_wise_metrics['anticipation']['F1']:.4f}}, Surprise F1: {{class_wise_metrics['surprise']['F1']:.4f}}). The relatively lower precision for 'anger' and 'anticipation' suggests a higher rate of false positives, while the lower recall might indicate missed true positives. This could be attributed to the nuanced nature of these emotions, less distinct textual indicators, or potential data imbalances.

The thresholds, which vary per emotion, indicate the dynamic nature of classification, where some emotions require a lower confidence score to be activated (e.g., Anger at {{class_wise_metrics['anger']['Threshold']:.2f}}) while others need higher confidence (e.g., Fear at {{class_wise_metrics['fear']['Threshold']:.2f}}).

These results highlight areas for potential improvement, such as focusing on data augmentation or feature engineering for weaker performing classes. Overall, the model provides a solid foundation for emotion detection in Arabic text, with robust performance in several key emotional categories.

## Final Task

### Subtask:
Summarize the reported results obtained from the dataset evaluation.

## Summary:

### Data Analysis Key Findings

*   The GTHL-Emo model achieved a **Jaccard Score of 0.6402** and a **Mean Average Precision (mAP) of 0.7129** on the test set.
*   The overall **Hamming Loss was 0.0872**, indicating a relatively low rate of incorrect label predictions per sample.
*   The model demonstrated varying performance across different emotion classes.
    *   **Strongest performing emotions** were 'love' (F1-score: 0.7826, Average Precision: 0.8277), 'acceptance' (F1-score: 0.7560, Average Precision: 0.8361), and 'neutral' (F1-score: 0.7377, Average Precision: 0.8061). 'Fear' also showed strong F1-score (0.6966) and Average Precision (0.7238).
    *   **Weaker performing emotions** were 'anger' (F1-score: 0.5566, Average Precision: 0.5281), 'anticipation' (F1-score: 0.5609, Average Precision: 0.5847), and 'surprise' (F1-score: 0.5910, Average Precision: 0.6207).
*   The optimal classification thresholds varied per emotion, ranging from 0.28 for 'anger' to 0.47 for 'fear', suggesting different confidence requirements for activating each emotion label.

### Insights or Next Steps

*   Further investigation into the 'anger', 'anticipation', and 'surprise' emotion classes is recommended to address their lower F1-scores. This could involve exploring data augmentation, more targeted feature engineering, or re-evaluating the labels for these specific emotions.
*   The robust performance in 'love', 'acceptance', and 'neutral' indicates the model's strong foundation in identifying certain emotional states within Arabic text, which can be leveraged for specific applications or as a baseline for future improvements.
"""