# -*- coding: utf-8 -*-
"""GTHL-Emo_Proposed_model_SemEval2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ9iXrM08k8lTavJH2hm5kLZRoKRTJxo
"""

!pip install emoji
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from transformers import AutoTokenizer, AutoModel
from peft import LoraConfig, get_peft_model
import re
from tqdm import tqdm
import logging
from sklearn.metrics import jaccard_score, f1_score, precision_score, recall_score, confusion_matrix, average_precision_score, hamming_loss
import json
import matplotlib.pyplot as plt
import seaborn as sns
from torch.amp import GradScaler, autocast
from scipy import sparse
from scipy.stats import entropy
import shutil
import urllib3
import emoji
import time

# Disable urllib3 warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Configuration
CONFIG = {
    'seed': 42,
    'max_length': 128,
    'batch_size': 2,
    'epochs': 20,
    'learning_rate': 1e-5,
    'weight_decay': 0.02,
    'patience': 7,
    'data_paths': {
        'train': './train.xlsx',
        'dev': './validation.xlsx',
        'test': './test.xlsx',
    },
    'results_dir': './results/',
    'emotion_labels': ['anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise'],
    'lora_rank': 16,
    'embedding_dim': 768,
    'focal_lambda': 0.1,
    'graph_lambda': 0.1,
    'ranking_lambda': 0.1,
    'temperature': 0.07,
    'mc_dropout_samples': 5,
    'gcn_hidden_dim': 768,
    'similarity_threshold': 0.5,
    'min_lambda': 0.05,
    'ema_alpha': 0.95,
    'gcn_layers': 1,
    'top_k_spans': 5,
    'lambda1': 0.5,
    'lambda2': 0.5,
    'graphsage_neighbors': 5,
    'label_transformer_layers': 2,
    'label_transformer_heads': 8,
    'verbose_logging': True,
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    'min_valid_tokens': 3
}

# Emoji mapping (updated for SemEval emotions)
emoji_map = {
    '😠': 'غاضب', '�41': 'غاضب', '🤬': 'غاضب', '💢': 'غاضب', '😤': 'غاضب', '😾': 'غاضب', '💪': 'غاضب',
    '🤢': 'مقرف', '🤮': 'مقرف', '🤧': 'مقرف', '😫': 'مقرف', '🥴': 'مقرف',
    '😨': 'خائف', '😱': 'خائف', '😰': 'خائف', '😥': 'خائف', '🥶': 'خائف', '😖': 'خائف',
    '😊': 'سعيد', '😃': 'سعيد', '😄': 'سعيد', '😁': 'سعيد', '🤗': 'سعيد', '😂': 'سعيد', '🤣': 'سعيد',
    '😅': 'سعيد', '😆': 'سعيد', '🎉': 'سعيد', '✨': 'سعيد',
    '😔': 'حزين', '😕': 'حزين', '😩': 'حزين', '🥺': 'حزين', '😣': 'حزين', '😟': 'حزين', '🤦': 'حزين', '👎': 'حزين',
    '😢': 'حزين', '😭': 'حزين', '😥': 'حزين', '💔': 'حزين', '😪': 'حزين', '🥀': 'حزين', '😿': 'حزين', '😴': 'حزين', '🎭': 'حزين',
    '😮': 'مندهش', '😯': 'مندهش', '😲': 'مندهش', '😳': 'مندهش', '🤯': 'مندهش', '😱': 'مندهش'
}

# Setup directories and logging
os.makedirs(CONFIG['results_dir'], exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(CONFIG['results_dir'], 'pipeline.log')),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger()

# Set random seed
def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_random_seed(CONFIG['seed'])
device = torch.device(CONFIG['device'])
device_type = CONFIG['device']
print(f"Using device: {device} (device_type: {device_type})")
logger.info(f"Using device: {device} (device_type: {device_type})")

# Disk space management
def check_disk_space(path):
    stat = shutil.disk_usage(path)
    free_space = stat.free / (1024 ** 3)  # Free space in GB
    logger.info(f"Free disk space in {path}: {free_space:.2f} GB")
    print(f"Free disk space in {path}: {free_space:.2f} GB")
    return free_space > 1

def cleanup_old_models(directory):
    for file in os.listdir(directory):
        if file.endswith('.pth'):
            try:
                os.remove(os.path.join(directory, file))
                logger.info(f"Removed old model file: {file}")
                print(f"Removed old model file: {file}")
            except Exception as e:
                logger.warning(f"Failed to remove {file}: {e}")
                print(f"Failed to remove {file}: {e}")

# Preprocessing
def compute_text_complexity(text):
    tokens = tokenize_text(text)
    unique_tokens = len(set(tokens))
    avg_token_length = np.mean([len(t) for t in tokens]) if tokens else 1.0
    return unique_tokens / len(tokens) if tokens else 0.0, avg_token_length

def tokenize_text(text, complexity=0.5):
    if complexity > 0.7:
        tokens = re.findall(r'\w+|[^\w\s]', text, re.UNICODE)
    else:
        tokens = text.split()
    return tokens

def preprocess_text(text, complexity=None):
    if not isinstance(text, str) or not text.strip():
        return "[EMPTY]"
    for emoji_char, emotion_word in emoji_map.items():
        text = text.replace(emoji_char, f" {emotion_word} ")
    text = emoji.demojize(text, language='ar')
    text = re.sub(r'http\S+|www.\S+', '', text)
    text = re.sub(r'#\w+', '', text)
    complexity_score, avg_token_length = compute_text_complexity(text) if complexity is None else (complexity, 1.0)
    tokens = tokenize_text(text, complexity_score)
    text = " ".join(tokens)
    text = re.sub(r'[^\w\s\U0001F600-\U0001F64F]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text if text else "[EMPTY]"

def preprocess_data(df):
    df = df.copy()
    df.columns = df.columns.str.strip()
    logger.info(f"Dataset columns: {list(df.columns)}")
    print(f"Dataset columns: {list(df.columns)}")
    if 'content' not in df.columns:
        raise ValueError("Expected 'content' column in dataset")
    df = df.dropna(subset=['content']).reset_index(drop=True)
    tokenizer = AutoTokenizer.from_pretrained("UBC-NLP/MARBERT", use_fast=True, cache_dir='./cache')

    # Preprocess texts and check token count
    processed_texts = []
    valid_indices = []
    for idx, text in enumerate(tqdm(df['content'], desc="Preprocessing texts")):
        processed_text = preprocess_text(text)
        if processed_text == "[EMPTY]":
            logger.warning(f"Text at index {idx} is empty after preprocessing")
            continue
        # Tokenize to check valid token count
        enc = tokenizer(
            processed_text,
            padding=False,
            truncation=True,
            max_length=CONFIG['max_length'],
            return_tensors='pt'
        )
        input_ids = enc['input_ids'][0]
        valid_tokens = input_ids.ne(tokenizer.pad_token_id).sum().item() - 2  # Exclude [CLS], [SEP]
        if valid_tokens < CONFIG['min_valid_tokens']:
            logger.warning(f"Text at index {idx}: '{processed_text}' has too few valid tokens ({valid_tokens})")
            continue
        processed_texts.append(processed_text)
        valid_indices.append(idx)

    df = df.iloc[valid_indices].reset_index(drop=True)
    df['text'] = processed_texts

    # Remove samples with no labels
    emotion_cols = CONFIG['emotion_labels']
    for col in emotion_cols:
        if col not in df.columns:
            raise ValueError(f"Missing emotion column: {col}")
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)
        logger.info(f"{col} unique values after preprocessing: {df[col].unique()}")
        print(f"{col} unique values after preprocessing: {df[col].unique()}")
    no_labels = df[emotion_cols].sum(axis=1) == 0
    logger.info(f"Samples with no labels before filtering: {no_labels.sum()}")
    print(f"Samples with no labels before filtering: {no_labels.sum()}")
    df = df[~no_labels].reset_index(drop=True)
    logger.info(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    print(f"Samples with no labels after filtering: {(df[emotion_cols].sum(axis=1) == 0).sum()}")
    return df

# Load dataset
def load_dataset(data_paths, results_dir):
    train_df = pd.read_excel(data_paths['train'])
    dev_df = pd.read_excel(data_paths['dev'])
    test_df = pd.read_excel(data_paths['test'])
    train_df.to_csv(os.path.join(results_dir, 'train_split.csv'), index=False)
    dev_df.to_csv(os.path.join(results_dir, 'dev_split.csv'), index=False)
    test_df.to_csv(os.path.join(results_dir, 'test_split.csv'), index=False)
    return train_df, dev_df, test_df

# Adaptive Lambda Network
class LambdaNet(nn.Module):
    def __init__(self, input_dim=2):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 2),
            nn.Sigmoid()
        )

    def forward(self, x):
        lambdas = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        return lambdas

# Adaptive GraphSAGE Layer
class AdaptiveGraphSAGELayer(nn.Module):
    def __init__(self, in_features, out_features, max_neighbors=10):
        super().__init__()
        self.fc_self = nn.Linear(in_features, out_features)
        self.fc_neigh = nn.Linear(in_features, out_features)
        self.norm = nn.LayerNorm(out_features)
        self.max_neighbors = max_neighbors
        self.aggregator_weights = nn.Parameter(torch.ones(3) / 3)

    def forward(self, h, adj, num_neighbors):
        batch_size = h.size(0)
        _, topk_indices = torch.topk(adj, min(num_neighbors, adj.size(1)), dim=1)
        h_neigh_mean = torch.zeros_like(h)
        h_neigh_max = torch.zeros_like(h)
        h_neigh_attn = torch.zeros_like(h)

        for i in range(batch_size):
            neigh_indices = topk_indices[i]
            if neigh_indices.numel() > 0:
                h_neigh_mean[i] = torch.mean(h[neigh_indices], dim=0)
                h_neigh_max[i] = torch.max(h[neigh_indices], dim=0)[0]
                attn_scores = F.softmax(torch.matmul(h[neigh_indices], h[i].unsqueeze(-1)), dim=0)
                h_neigh_attn[i] = torch.sum(h[neigh_indices] * attn_scores, dim=0)

        aggregator_weights = F.softmax(self.aggregator_weights, dim=0)
        h_neigh = (aggregator_weights[0] * h_neigh_mean +
                   aggregator_weights[1] * h_neigh_max +
                   aggregator_weights[2] * h_neigh_attn)

        h_self = self.fc_self(h)
        h_neigh = self.fc_neigh(h_neigh)
        h_prime = h_self + h_neigh
        h_prime = self.norm(F.relu(h_prime))
        return h_prime

# Adaptive Loss Weight Network
class LossWeightNet(nn.Module):
    def __init__(self, input_dim=1):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 3),
            nn.Sigmoid()
        )
        self.prev_weights = None
        self.ema_alpha = CONFIG['ema_alpha']

    def forward(self, x):
        weights = self.fc(x) * (1 - CONFIG['min_lambda']) + CONFIG['min_lambda']
        if self.prev_weights is not None:
            weights = self.ema_alpha * self.prev_weights + (1 - self.ema_alpha) * weights
        self.prev_weights = weights.detach()
        return weights

# GTHL-Emo-Emo Model
class GTHLEmo(nn.Module):
    def __init__(self, num_emotions, embedding_dim=768, gcn_hidden_dim=768, gcn_layers=1):
        super().__init__()
        self.num_emotions = num_emotions
        self.embedding_dim = embedding_dim
        self.gcn_layers = gcn_layers

        model_name = "UBC-NLP/MARBERT"
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True, cache_dir='./cache')
            self.transformer = AutoModel.from_pretrained(model_name, cache_dir='./cache')
        except Exception as e:
            logger.error(f"Failed to download {model_name}: {e}")
            raise RuntimeError(f"Ensure network connectivity or pre-download {model_name} to ./cache")

        lora_config = LoraConfig(
            r=CONFIG['lora_rank'],
            lora_alpha=16,
            target_modules=["query", "key", "value", "dense"],
            lora_dropout=0.1
        )
        self.transformer = get_peft_model(self.transformer, lora_config)

        self.attention_weight = nn.Parameter(torch.randn(embedding_dim))
        self.attention_bias = nn.Parameter(torch.tensor(0.0))
        self.attention_fc = nn.Linear(embedding_dim, embedding_dim)

        self.gcn_layers_list = nn.ModuleList([
            AdaptiveGraphSAGELayer(embedding_dim if i == 0 else gcn_hidden_dim, gcn_hidden_dim, CONFIG['graphsage_neighbors'])
            for i in range(gcn_layers)
        ])

        self.fusion_fc = nn.Linear(embedding_dim * 2, embedding_dim)
        self.fusion_norm = nn.LayerNorm(embedding_dim)

        self.label_embeddings = nn.Parameter(torch.randn(num_emotions, embedding_dim))
        self.label_transformer_layers = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=embedding_dim,
                nhead=CONFIG['label_transformer_heads'],
                dim_feedforward=512,
                dropout=0.1,
                batch_first=True
            ) for _ in range(CONFIG['label_transformer_layers'])
        ])

        self.classifier = nn.Linear(embedding_dim, num_emotions)
        self.classifier_bias = nn.Parameter(torch.zeros(num_emotions))

        self.lambda_net = LambdaNet().to(device)
        self.loss_weight_net = LossWeightNet().to(device)
        self.emoji_cooccurrence = {}
        self.emoji_embeddings = nn.ParameterDict()

        self.loss_fn = GTHLEmoLoss(
            focal_lambda=CONFIG['focal_lambda'],
            graph_lambda=CONFIG['graph_lambda'],
            ranking_lambda=CONFIG['ranking_lambda'],
            num_emotions=num_emotions,
            similarity_threshold=CONFIG['similarity_threshold']
        )

        self.to(device)

    def update_emoji_embeddings(self, texts, labels):
        for text, label in zip(texts, labels):
            emojis = re.findall(r'\U0001F600-\U0001F64F', text)
            for e in emojis:
                if e not in self.emoji_cooccurrence:
                    self.emoji_cooccurrence[e] = np.zeros(self.num_emotions)
                for i, val in enumerate(label):
                    if val == 1:
                        self.emoji_cooccurrence[e][i] += 1
        for e in self.emoji_cooccurrence:
            if e not in self.emoji_embeddings:
                embedding = torch.randn(self.embedding_dim, device=device, requires_grad=True)
                self.emoji_embeddings[e] = nn.Parameter(embedding)
            else:
                counts = torch.tensor(self.emoji_cooccurrence[e], dtype=torch.float32, device=device)
                norm_counts = counts / (counts.sum() + 1e-7)
                emotion_emb = self.label_embeddings @ norm_counts
                self.emoji_embeddings[e].data = 0.9 * self.emoji_embeddings[e].data + 0.1 * emotion_emb

    def preprocess_with_emoji(self, text):
        if not isinstance(text, str) or not text.strip():
            return "[EMPTY]"
        for emoji_char, embedding in self.emoji_embeddings.items():
            if emoji_char in text:
                emotion_idx = torch.topk(torch.matmul(F.normalize(embedding, dim=0), F.normalize(self.label_embeddings, dim=1).t()), 1).indices.item()
                emotion_word = CONFIG['emotion_labels'][emotion_idx]
                text = text.replace(emoji_char, f" {emotion_word} ")
        return preprocess_text(text)

    def prepare_inputs(self, texts):
        valid_texts = [self.preprocess_with_emoji(t) for t in texts if isinstance(t, str) and t.strip() and self.preprocess_with_emoji(t) != "[EMPTY]"]
        if not valid_texts:
            logger.warning("No valid texts in batch; returning dummy input")
            return {'input_ids': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((1, CONFIG['max_length']), dtype=torch.long, device=device)}
        try:
            enc = self.tokenizer(
                valid_texts,
                padding='max_length',
                truncation=True,
                max_length=CONFIG['max_length'],
                return_tensors='pt',
                return_attention_mask=True
            )
            input_ids = enc['input_ids']
            attention_mask = enc['attention_mask']
            return {'input_ids': input_ids.to(device), 'attention_mask': attention_mask.to(device)}
        except Exception as e:
            logger.error(f"Tokenization failed: {e}")
            return {'input_ids': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device),
                    'attention_mask': torch.zeros((len(texts), CONFIG['max_length']), dtype=torch.long, device=device)}

    def compute_adjacency(self, h_span, labels=None):
        batch_size = h_span.size(0)
        if batch_size <= 1:
            return torch.eye(batch_size, device=h_span.device), 1.0
        h_span_norm = F.normalize(h_span, dim=1)
        cosine_sim = torch.matmul(h_span_norm, h_span_norm.t()).cpu().detach().numpy()
        similarity_threshold = np.percentile(cosine_sim.flatten(), 75) if cosine_sim.size > 1 else CONFIG['similarity_threshold']

        if labels is None:
            sim = cosine_sim
        else:
            labels_np = labels.cpu().numpy()
            jaccard_sim = np.zeros((batch_size, batch_size))
            for i in range(batch_size):
                for j in range(batch_size):
                    jaccard_sim[i, j] = jaccard_score(labels_np[i], labels_np[j], zero_division=0)
            mean_cosine = np.mean(cosine_sim)
            label_entropy = entropy(labels_np.sum(axis=0) / (labels_np.sum() + 1e-7))
            lambda_inputs = torch.tensor([mean_cosine, label_entropy], dtype=torch.float32, device=h_span.device).unsqueeze(0)
            lambda1, lambda2 = self.lambda_net(lambda_inputs)[0]
            sim = lambda1.item() * jaccard_sim + lambda2.item() * cosine_sim

        adj = sparse.csr_matrix((sim > similarity_threshold).astype(float))
        adj = adj + sparse.eye(batch_size, format='csr')
        degree = np.array(adj.sum(axis=1)).flatten()
        degree_inv_sqrt = sparse.diags(1.0 / np.sqrt(degree + 1e-7))
        adj_norm = degree_inv_sqrt @ adj @ degree_inv_sqrt
        return torch.tensor(adj_norm.toarray(), dtype=torch.float32, device=h_span.device), degree.mean()

    def forward(self, texts, labels=None, training=True, return_spans=False):
        if training and labels is not None:
            self.update_emoji_embeddings(texts, labels.cpu().numpy())
        inputs = self.prepare_inputs(texts)
        outputs = self.transformer(input_ids=inputs['input_ids'], attention_mask=inputs['attention_mask'])
        hidden_states = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']

        scores = torch.matmul(hidden_states, self.attention_weight) + self.attention_bias
        scores = torch.clamp(scores, -1e4, 1e4)
        scores = scores.masked_fill(attention_mask == 0, -1e4)
        alpha = F.softmax(scores, dim=1)
        h_span = torch.sum(hidden_states * alpha.unsqueeze(-1), dim=1)
        h_span = self.attention_fc(h_span)

        adj, avg_degree = self.compute_adjacency(h_span, labels)
        num_neighbors = max(2, min(CONFIG['graphsage_neighbors'], int(avg_degree)))

        h_graph = h_span
        for layer in self.gcn_layers_list:
            h_graph = layer(h_graph, adj, num_neighbors)

        h_fused = torch.cat([h_span, h_graph], dim=-1)
        h_fused = self.fusion_norm(F.relu(self.fusion_fc(h_fused)))

        label_emb = self.label_embeddings.unsqueeze(1)
        for layer in self.label_transformer_layers:
            label_emb = layer(label_emb)
        label_emb = label_emb.squeeze(1)

        logits = self.classifier(h_fused) + self.classifier_bias
        y_hat = torch.sigmoid(logits)

        if return_spans:
            span_scores = torch.einsum('bld,cd->blc', hidden_states, label_emb)
            span_attn = F.softmax(span_scores.masked_fill(attention_mask.unsqueeze(-1) == 0, -1e4), dim=1)
            return y_hat, span_attn, inputs['input_ids']
        return y_hat

# Adaptive Loss Function
class GTHLEmoLoss(nn.Module):
    def __init__(self, focal_lambda=0.1, graph_lambda=0.1, ranking_lambda=0.1, num_emotions=6, similarity_threshold=0.5):
        super().__init__()
        self.base_focal_lambda = focal_lambda
        self.base_graph_lambda = graph_lambda
        self.base_ranking_lambda = ranking_lambda
        self.num_emotions = num_emotions
        self.similarity_threshold = similarity_threshold
        self.margin = 0.5

    def bce_loss(self, y_pred, y_true):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        return -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()

    def focal_loss(self, y_pred, y_true, alpha=0.25, gamma=2.0):
        y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)
        pt = y_true * y_pred + (1 - y_true) * (1 - y_pred)
        focal = -alpha * (1 - pt) ** gamma * torch.log(pt)
        return focal.mean()

    def ranking_loss(self, y_pred, y_true):
        batch_size, num_labels = y_pred.size()
        loss = torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        for i in range(batch_size):
            pos_indices = y_true[i].nonzero(as_tuple=True)[0]
            neg_indices = (1 - y_true[i]).nonzero(as_tuple=True)[0]
            if len(pos_indices) == 0 or len(neg_indices) == 0:
                continue
            pos_scores = y_pred[i, pos_indices]
            neg_scores = y_pred[i, neg_indices]
            diff = pos_scores.unsqueeze(1) - neg_scores.unsqueeze(0)
            loss = loss + F.relu(self.margin - diff).mean()
        return loss / (batch_size + 1e-7)

    def graph_kl_loss(self, label_emb, y_true):
        A = torch.matmul(y_true.t(), y_true) / (y_true.size(0) + 1e-7)
        L_norm = F.normalize(label_emb, dim=1)
        Q = torch.matmul(L_norm, L_norm.t())
        A = F.softmax(A, dim=1)
        Q = F.softmax(Q, dim=1)
        kl = F.kl_div(Q.log(), A, reduction='batchmean')
        return torch.clamp(kl, 0, 10)

    def compute_adaptive_focal_params(self, y_true):
        class_counts = y_true.sum(dim=0).cpu().numpy()
        total = y_true.sum().item() + 1e-7
        class_freq = class_counts / total
        alpha = 1.0 - class_freq / (class_freq.max() + 1e-7)
        alpha = np.clip(alpha, 0.1, 0.9)
        gamma = 2.0 + 2.0 * entropy(class_freq)
        return alpha.mean(), min(gamma, 4.0)

    def forward(self, y_pred, y_true, label_emb=None, loss_weight_net=None, jaccard_score=None):
        bce = self.bce_loss(y_pred, y_true)
        alpha, gamma = self.compute_adaptive_focal_params(y_true)
        focal = self.focal_loss(y_pred, y_true, alpha, gamma) if self.base_focal_lambda is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        ranking = self.ranking_loss(y_pred, y_true) if self.base_ranking_lambda is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)
        graph_kl = self.graph_kl_loss(label_emb, y_true) if label_emb is not None else torch.tensor(0.0, device=y_pred.device, requires_grad=True)

        if loss_weight_net is not None and jaccard_score is not None:
            weights = loss_weight_net(torch.tensor([jaccard_score], dtype=torch.float32, device=y_pred.device).unsqueeze(0))
            focal_lambda, graph_lambda, ranking_lambda = weights[0]
        else:
            focal_lambda = self.base_focal_lambda
            graph_lambda = self.base_graph_lambda
            ranking_lambda = self.base_ranking_lambda

        total_loss = bce + focal_lambda * focal + ranking_lambda * ranking + graph_lambda * graph_kl
        return total_loss, bce, focal, ranking, graph_kl

# Training Function
def train_model(model, train_texts, val_texts, train_labels, val_labels, weights_file):
    print("Training model")
    logger.info("Training model")
    optimizer = optim.AdamW(model.parameters(), lr=CONFIG['learning_rate'], weight_decay=CONFIG['weight_decay'])
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=3)
    scaler = GradScaler()
    best_val_jaccard = 0
    patience_counter = 0
    history = {
        'loss': [], 'val_loss': [],
        'bce_loss': [], 'val_bce_loss': [],
        'focal_loss': [], 'val_focal_loss': [],
        'ranking_loss': [], 'val_ranking_loss': [],
        'graph_kl_loss': [], 'val_graph_kl_loss': [],
        'jaccard': [], 'val_jaccard': []
    }

    train_batches = (len(train_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    val_batches = (len(val_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']

    for epoch in range(CONFIG['epochs']):
        model.train()
        train_loss = train_bce_loss = train_focal_loss = train_ranking_loss = train_graph_kl_loss = train_jaccard = 0
        valid_train_batches = 0

        train_pbar = tqdm(range(train_batches), desc=f"Epoch {epoch+1} Training (Jaccard: 0.0000)", leave=True)
        for i in train_pbar:
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(train_texts))
            batch_texts = train_texts[start:end]
            batch_labels = train_labels[start:end]

            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                logger.warning(f"Skipping batch {i+1}: empty texts or no labels")
                continue

            batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

            optimizer.zero_grad()
            with autocast(device_type=device_type):
                try:
                    y_hat = model(batch_texts, labels=batch_labels)
                    loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                        y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                        train_jaccard / max(valid_train_batches, 1)
                    )
                except Exception as e:
                    logger.warning(f"Error in batch {i+1}: {e}")
                    continue

            if torch.isnan(loss) or torch.isinf(loss):
                logger.warning(f"Invalid loss detected in batch {i+1}: {loss.item()}")
                print(f"Invalid loss detected in batch {i+1}: {loss.item()}")
                continue

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
            scaler.step(optimizer)
            scaler.update()

            preds = (y_hat.detach() > 0.5).float()
            batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

            train_loss += loss.item()
            train_bce_loss += bce_loss.item()
            train_focal_loss += focal_loss.item()
            train_ranking_loss += ranking_loss.item()
            train_graph_kl_loss += graph_kl_loss.item()
            train_jaccard += batch_jaccard
            valid_train_batches += 1

            train_pbar.set_postfix({'Jaccard': f"{train_jaccard / valid_train_batches:.4f}"})
            train_pbar.set_description(f"Epoch {epoch+1} Training (Jaccard: {train_jaccard / valid_train_batches:.4f})")

            torch.cuda.empty_cache()

        if valid_train_batches > 0:
            train_loss /= valid_train_batches
            train_bce_loss /= valid_train_batches
            train_focal_loss /= valid_train_batches
            train_ranking_loss /= valid_train_batches
            train_graph_kl_loss /= valid_train_batches
            train_jaccard /= valid_train_batches

        # Validation
        model.eval()
        val_loss = val_bce_loss = val_focal_loss = val_ranking_loss = val_graph_kl_loss = val_jaccard = 0
        valid_val_batches = 0

        val_pbar = tqdm(range(val_batches), desc=f"Epoch {epoch+1} Validation (Jaccard: 0.0000)", leave=True)
        with torch.no_grad():
            for i in val_pbar:
                start = i * CONFIG['batch_size']
                end = min(start + CONFIG['batch_size'], len(val_texts))
                batch_texts = val_texts[start:end]
                batch_labels = val_labels[start:end]

                if not batch_texts or all(t == "[EMPTY]" for t in batch_texts) or not np.any(batch_labels):
                    continue

                batch_labels = torch.tensor(batch_labels, dtype=torch.float32).to(device)

                with autocast(device_type=device_type):
                    try:
                        y_hat = model(batch_texts, labels=batch_labels)
                        loss, bce_loss, focal_loss, ranking_loss, graph_kl_loss = model.loss_fn(
                            y_hat, batch_labels, model.label_embeddings, model.loss_weight_net,
                            val_jaccard / max(valid_val_batches, 1)
                        )
                    except Exception as e:
                        logger.warning(f"Error in validation batch {i+1}: {e}")
                        continue

                preds = (y_hat.detach() > 0.5).float()
                batch_jaccard = jaccard_score(batch_labels.cpu().numpy(), preds.cpu().numpy(), average='samples', zero_division=0)

                val_loss += loss.item()
                val_bce_loss += bce_loss.item()
                val_focal_loss += focal_loss.item()
                val_ranking_loss += ranking_loss.item()
                val_graph_kl_loss += graph_kl_loss.item()
                val_jaccard += batch_jaccard
                valid_val_batches += 1

                val_pbar.set_postfix({'Jaccard': f"{val_jaccard / valid_val_batches:.4f}"})
                val_pbar.set_description(f"Epoch {epoch+1} Validation (Jaccard: {val_jaccard / valid_val_batches:.4f})")

                torch.cuda.empty_cache()

        if valid_val_batches > 0:
            val_loss /= valid_val_batches
            val_bce_loss /= valid_val_batches
            val_focal_loss /= valid_val_batches
            val_ranking_loss /= valid_val_batches
            val_graph_kl_loss /= valid_val_batches
            val_jaccard /= valid_val_batches

        # Log and store history
        print(f"\nEpoch {epoch+1} Summary:")
        print(f"Train Loss: {train_loss:.4f} (BCE: {train_bce_loss:.4f}, Focal: {train_focal_loss:.4f}, Ranking: {train_ranking_loss:.4f}, Graph KL: {train_graph_kl_loss:.4f})")
        print(f"Train Jaccard: {train_jaccard:.4f}")
        print(f"Val Loss: {val_loss:.4f} (BCE: {val_bce_loss:.4f}, Focal: {val_focal_loss:.4f}, Ranking: {val_ranking_loss:.4f}, Graph KL: {val_graph_kl_loss:.4f})")
        print(f"Val Jaccard: {val_jaccard:.4f}")

        history['loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['bce_loss'].append(train_bce_loss)
        history['val_bce_loss'].append(val_bce_loss)
        history['focal_loss'].append(train_focal_loss)
        history['val_focal_loss'].append(val_focal_loss)
        history['ranking_loss'].append(train_ranking_loss)
        history['val_ranking_loss'].append(val_ranking_loss)
        history['graph_kl_loss'].append(train_graph_kl_loss)
        history['val_graph_kl_loss'].append(val_graph_kl_loss)
        history['jaccard'].append(train_jaccard)
        history['val_jaccard'].append(val_jaccard)

        scheduler.step()

        if val_jaccard > best_val_jaccard:
            best_val_jaccard = val_jaccard
            if check_disk_space(CONFIG['results_dir']):
                torch.save(model.state_dict(), weights_file)
                print(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
                logger.info(f"Saved best model with Val Jaccard: {best_val_jaccard:.4f}")
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= CONFIG['patience']:
                print(f"Early stopping at epoch {epoch+1}")
                logger.info(f"Early stopping at epoch {epoch+1}")
                break

        check_disk_space(CONFIG['results_dir'])

    if os.path.exists(weights_file):
        model.load_state_dict(torch.load(weights_file))
        print(f"Loaded best model from {weights_file}")
        logger.info(f"Loaded best model from {weights_file}")
    else:
        print(f"No saved model found at {weights_file}")
        logger.warning(f"No saved model found at {weights_file}")

    pd.DataFrame(history).to_csv(os.path.join(CONFIG['results_dir'], 'training_history.csv'), index=False)
    return model, history

# Evaluation
def evaluate_classifier(model, texts, labels, split='test'):
    logger.info(f"Evaluating classifier on {split} split")
    print(f"Evaluating classifier on {split} split")
    model.eval()
    num_batches = (len(texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']
    preds_proba = []
    span_attns = []
    input_ids_list = []

    with torch.no_grad():
        for i in tqdm(range(num_batches), desc=f"Evaluating {split}", leave=False):
            start = i * CONFIG['batch_size']
            end = min(start + CONFIG['batch_size'], len(texts))
            batch_texts = texts[start:end]
            if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                continue
            with autocast(device_type=device_type):
                try:
                    y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                    preds_proba.append(y_hat.cpu().float())
                    span_attns.append(span_attn.cpu())
                    input_ids_list.append(input_ids.cpu())
                except Exception as e:
                    logger.warning(f"Error in evaluation batch {i+1}: {e}")
                    continue
            torch.cuda.empty_cache()

    if not preds_proba:
        logger.warning(f"No valid predictions for {split} split")
        return {}, {}, np.zeros_like(labels), {}, {}

    preds_proba = torch.cat(preds_proba, dim=0).numpy()
    span_attn = torch.cat(span_attns, dim=0)
    input_ids = torch.cat(input_ids_list, dim=0)
    labels = np.array(labels)

    thresholds = np.arange(0.1, 0.5, 0.01)
    best_thresholds = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        best_jaccard = 0
        best_t = 0.5
        for t in thresholds:
            preds = (preds_proba[:, i] >= t).astype(int)
            j = jaccard_score(labels[:, i], preds, zero_division=0)
            if j > best_jaccard:
                best_jaccard = j
                best_t = t
        best_thresholds[label] = best_t

    preds = np.zeros_like(preds_proba)
    for i, label in enumerate(CONFIG['emotion_labels']):
        preds[:, i] = (preds_proba[:, i] >= best_thresholds[label]).astype(int)

    ap_scores = []
    no_positive_labels = []
    for i, label in enumerate(CONFIG['emotion_labels']):
        positive_count = np.sum(labels[:, i])
        logger.info(f"{split} set - {label}: {positive_count} positive samples")
        print(f"{split} set - {label}: {positive_count} positive samples")
        if positive_count == 0:
            logger.warning(f"No positive samples for label {label} in {split} set; skipping Average Precision")
            no_positive_labels.append(label)
            continue
        ap = average_precision_score(labels[:, i], preds_proba[:, i])
        if not np.isnan(ap):
            ap_scores.append(ap)

    metrics = {
        'jaccard': jaccard_score(labels, preds, average='samples', zero_division=0),
        'hamming_loss': hamming_loss(labels, preds),
        'precision': precision_score(labels, preds, average='samples', zero_division=0),
        'recall': recall_score(labels, preds, average='samples', zero_division=0),
        'f1': f1_score(labels, preds, average='samples', zero_division=0),
        'micro_precision': precision_score(labels, preds, average='micro', zero_division=0),
        'micro_recall': recall_score(labels, preds, average='micro', zero_division=0),
        'micro_f1': f1_score(labels, preds, average='micro', zero_division=0),
        'macro_precision': precision_score(labels, preds, average='macro', zero_division=0),
        'macro_recall': recall_score(labels, preds, average='macro', zero_division=0),
        'macro_f1': f1_score(labels, preds, average='macro', zero_division=0),
        'mean_average_precision': np.mean(ap_scores) if ap_scores else np.nan
    }

    class_metrics = {}
    confusion_matrices = {}
    for i, label in enumerate(CONFIG['emotion_labels']):
        class_metrics[label] = {
            'precision': precision_score(labels[:, i], preds[:, i], zero_division=0),
            'recall': recall_score(labels[:, i], preds[:, i], zero_division=0),
            'f1': f1_score(labels[:, i], preds[:, i], zero_division=0),
            'average_precision': average_precision_score(labels[:, i], preds_proba[:, i]) if np.sum(labels[:, i]) > 0 else np.nan,
            'threshold': best_thresholds[label]
        }
        cm = confusion_matrix(labels[:, i], preds[:, i])
        confusion_matrices[label] = cm
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
        plt.title(f'Confusion Matrix for {label}')
        plt.xlabel('Predicted')
        plt.ylabel('True')
        plt.savefig(os.path.join(CONFIG['results_dir'], f'confusion_matrix_{label}_{split}.png'), bbox_inches='tight')
        plt.close()

    for i in range(min(5, len(texts))):
        if all(t == "[EMPTY]" for t in texts[i:i+1]):
            continue
        for j, emotion in enumerate(CONFIG['emotion_labels']):
            if preds[i, j] == 1:
                attn_scores = span_attn[i, :, j]  # Keep as tensor
                valid_length = input_ids[i].ne(model.tokenizer.pad_token_id).sum().item()
                k = min(CONFIG['top_k_spans'], valid_length)
                if k > 0:
                    top_k_idx = torch.topk(attn_scores[:valid_length], k).indices
                    tokens = model.tokenizer.convert_ids_to_tokens(input_ids[i][top_k_idx])
                    tokens = [token.replace('##', '') for token in tokens]
                    attn_scores_np = attn_scores[top_k_idx].cpu().numpy()  # Convert only selected scores to NumPy
                    plt.figure(figsize=(12, 2))
                    sns.heatmap([attn_scores_np], xticklabels=tokens, cmap='Blues', annot=True, fmt='.2f')
                    plt.title(f'Attention Heatmap for {emotion} (Sample {i+1})')
                    plt.xlabel('Tokens')
                    plt.ylabel('Attention')
                    plt.savefig(os.path.join(CONFIG['results_dir'], f'attention_heatmap_sample_{i+1}_{emotion}_{split}.png'), bbox_inches='tight')
                    plt.close()

    return metrics, class_metrics, preds, best_thresholds, confusion_matrices

# Inference
def infer_emotions(model, texts, thresholds, use_mc_dropout=False):
    logger.info("Performing inference")
    print("Performing inference")
    model.eval()
    processed_texts = [model.preprocess_with_emoji(text) for text in texts]
    num_batches = (len(processed_texts) + CONFIG['batch_size'] - 1) // CONFIG['batch_size']

    if use_mc_dropout:
        model.train()
        all_preds_proba = []
        all_span_attns = []
        all_input_ids = []
        for _ in range(CONFIG['mc_dropout_samples']):
            preds_proba = []
            span_attns = []
            input_ids_list = []
            with torch.no_grad():
                for i in range(num_batches):
                    start = i * CONFIG['batch_size']
                    end = min(start + CONFIG['batch_size'], len(processed_texts))
                    batch_texts = processed_texts[start:end]
                    if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                        continue
                    with autocast(device_type=device_type):
                        try:
                            y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                            preds_proba.append(y_hat.cpu().float())
                            span_attns.append(span_attn.cpu())
                            input_ids_list.append(input_ids.cpu())
                        except Exception as e:
                            logger.warning(f"Error in inference batch {i+1}: {e}")
                            continue
                    torch.cuda.empty_cache()
                if preds_proba:
                    all_preds_proba.append(torch.cat(preds_proba, dim=0))
                    all_span_attns.append(torch.cat(span_attns, dim=0))
                    all_input_ids.append(torch.cat(input_ids_list, dim=0))
        if not all_preds_proba:
            logger.warning("No valid predictions in MC dropout; returning empty results")
            return [{'text': t, 'processed_text': pt, 'emotions': ['none'], 'probabilities': {}, 'uncertainty': {}, 'attributed_spans': {}} for t, pt in zip(texts, processed_texts)]
        preds_proba = torch.stack(all_preds_proba).mean(dim=0).numpy()
        preds_std = torch.stack(all_preds_proba).std(dim=0).numpy()
        span_attn = torch.stack(all_span_attns).mean(dim=0)
        input_ids = all_input_ids[0]  # Take the first input_ids as they are identical across MC samples
    else:
        preds_proba = []
        span_attns = []
        input_ids_list = []
        with torch.no_grad():
            for i in range(num_batches):
                start = i * CONFIG['batch_size']
                end = min(start + CONFIG['batch_size'], len(processed_texts))
                batch_texts = processed_texts[start:end]
                if not batch_texts or all(t == "[EMPTY]" for t in batch_texts):
                    continue
                with autocast(device_type=device_type):
                    try:
                        y_hat, span_attn, input_ids = model(batch_texts, return_spans=True)
                        preds_proba.append(y_hat.cpu().float())
                        span_attns.append(span_attn.cpu())
                        input_ids_list.append(input_ids.cpu())
                    except Exception as e:
                        logger.warning(f"Error in inference batch {i+1}: {e}")
                        continue
                torch.cuda.empty_cache()
        if not preds_proba:
            logger.warning("No valid predictions; returning empty results")
            return [{'text': t, 'processed_text': pt, 'emotions': ['none'], 'probabilities': {}, 'uncertainty': {}, 'attributed_spans': {}} for t, pt in zip(texts, processed_texts)]
        preds_proba = torch.cat(preds_proba, dim=0).numpy()
        span_attn = torch.cat(span_attns, dim=0)
        input_ids = torch.cat(input_ids_list, dim=0)
        preds_std = np.zeros_like(preds_proba)

    preds = np.zeros_like(preds_proba)
    for i, label in enumerate(CONFIG['emotion_labels']):
        preds[:, i] = (preds_proba[:, i] >= thresholds[label]).astype(int)

    results = []
    for i, pred in enumerate(preds):
        emotions = [CONFIG['emotion_labels'][j] for j, val in enumerate(pred) if val == 1]
        attributed_spans = {}
        valid_length = input_ids[i].ne(model.tokenizer.pad_token_id).sum().item()
        for j, emotion in enumerate(CONFIG['emotion_labels']):
            if pred[j] == 1 and valid_length > 0:
                attn_scores = span_attn[i, :, j]  # Keep as tensor
                k = min(CONFIG['top_k_spans'], valid_length)
                if k > 0:
                    top_k_idx = torch.topk(attn_scores[:valid_length], k).indices
                    tokens = model.tokenizer.convert_ids_to_tokens(input_ids[i][top_k_idx])
                    tokens = [token.replace('##', '') for token in tokens]
                    attributed_spans[emotion] = tokens
        results.append({
            'text': texts[i],
            'processed_text': processed_texts[i],
            'emotions': emotions if emotions else ['none'],
            'probabilities': {CONFIG['emotion_labels'][j]: float(prob) for j, prob in enumerate(preds_proba[i])},
            'uncertainty': {CONFIG['emotion_labels'][j]: float(std) for j, std in enumerate(preds_std[i])} if use_mc_dropout else {},
            'attributed_spans': attributed_spans
        })
    return results

# Generate Test Predictions
def generate_test_predictions(model, test_texts, thresholds, output_file):
    logger.info("Generating test set predictions")
    print("Generating test set predictions")
    predictions = infer_emotions(model, test_texts, thresholds, use_mc_dropout=False)
    submission = pd.DataFrame({
        'ID': [text.split('\t')[0] if '\t' in text else f'sample_{i}' for i, text in enumerate(test_texts)],
        'text': test_texts
    })
    for label in CONFIG['emotion_labels']:
        submission[label] = [1 if pred['probabilities'][label] >= thresholds[label] else 0 for pred in predictions]
    submission.to_csv(output_file, index=False, sep='\t')
    logger.info(f"Saved test predictions to {output_file}")
    print(f"Saved test predictions to {output_file}")
    return submission

# Correlation Matrices
def compute_correlation_matrices(gt_labels, pred_labels, emotion_labels, results_dir):
    gt_labels = np.array(gt_labels)
    pred_labels = np.array(pred_labels)
    gt_corr = np.corrcoef(gt_labels.T)
    pred_corr = np.corrcoef(pred_labels.T)
    gt_corr = np.nan_to_num(gt_corr, nan=0.0)
    pred_corr = np.nan_to_num(pred_corr, nan=0.0)

    plt.figure(figsize=(10, 8))
    sns.heatmap(gt_corr, annot=True, fmt='.2f', cmap='Blues', xticklabels=emotion_labels, yticklabels=emotion_labels)
    plt.title('Ground Truth Correlation Matrix')
    plt.savefig(os.path.join(results_dir, 'gt_correlation_matrix.png'), bbox_inches='tight')
    plt.close()

    plt.figure(figsize=(10, 8))
    sns.heatmap(pred_corr, annot=True, fmt='.2f', cmap='Blues', xticklabels=emotion_labels, yticklabels=emotion_labels)
    plt.title('Predicted Correlation Matrix')
    plt.savefig(os.path.join(results_dir, 'pred_correlation_matrix.png'), bbox_inches='tight')
    plt.close()

    return gt_corr, pred_corr

# Main Execution
if __name__ == "__main__":
    print("Starting GTHL-Emo model training with MARBERT")
    logger.info("Starting GTHL-Emo model training with MARBERT")

    cleanup_old_models(CONFIG['results_dir'])
    train_df, val_df, test_df = load_dataset(CONFIG['data_paths'], CONFIG['results_dir'])
    train_processed = preprocess_data(train_df)
    val_processed = preprocess_data(val_df)
    test_processed = preprocess_data(test_df)
    train_labels = train_processed[CONFIG['emotion_labels']].values
    val_labels = val_processed[CONFIG['emotion_labels']].values
    test_labels = test_processed[CONFIG['emotion_labels']].values

    # Log test set positive samples
    for col in CONFIG['emotion_labels']:
        positive_count = np.sum(test_labels[:, CONFIG['emotion_labels'].index(col)])
        logger.info(f"Test set - {col}: {positive_count} positive samples")
        print(f"Test set - {col}: {positive_count} positive samples")

    train_processed.to_csv(os.path.join(CONFIG['results_dir'], 'train_processed.csv'), index=False)
    val_processed.to_csv(os.path.join(CONFIG['results_dir'], 'val_processed.csv'), index=False)
    test_processed.to_csv(os.path.join(CONFIG['results_dir'], 'test_processed.csv'), index=False)

    print("\nDataset Sizes:")
    print(f"Training set: {len(train_processed)} samples")
    print(f"Validation set: {len(val_processed)} samples")
    print(f"Test set: {len(test_processed)} samples")
    logger.info(f"Training set size: {len(train_processed)}")
    logger.info(f"Validation set size: {len(val_processed)}")
    logger.info(f"Test set size: {len(test_processed)}")

    print("\nTraining model...")
    model = GTHLEmo(
        num_emotions=len(CONFIG['emotion_labels']),
        embedding_dim=CONFIG['embedding_dim'],
        gcn_hidden_dim=CONFIG['gcn_hidden_dim'],
        gcn_layers=CONFIG['gcn_layers']
    )
    weights_file = os.path.join(CONFIG['results_dir'], 'best_model.pth')
    model, history = train_model(
        model,
        train_processed['text'].tolist(),
        val_processed['text'].tolist(),
        train_labels,
        val_labels,
        weights_file
    )

    val_metrics, val_class_metrics, val_preds, best_thresholds, val_confusion_matrices = evaluate_classifier(
        model, val_processed['text'].tolist(), val_labels, split='val'
    )

    print("\nEvaluating on test set...")
    test_metrics, test_class_metrics, test_preds, test_thresholds, test_confusion_matrices = evaluate_classifier(
        model, test_processed['text'].tolist(), test_labels, split='test'
    )
    print("\nTest Set Evaluation Results:")
    print(f"Test Jaccard Score: {test_metrics['jaccard']:.4f}")
    print(f"Test Hamming Loss: {test_metrics['hamming_loss']:.4f}")
    print(f"Test Mean Average Precision: {test_metrics['mean_average_precision']:.4f}")
    print("\nOverall Metrics:")
    for metric_name, value in test_metrics.items():
        print(f"{metric_name}: {value:.4f}")
    print("\nClass-wise Metrics:")
    for emotion, scores in test_class_metrics.items():
        print(f"{emotion}:")
        print(f"  Precision: {scores['precision']:.4f}")
        print(f"  Recall: {scores['recall']:.4f}")
        print(f"  F1: {scores['f1']:.4f}")
        print(f"  Average Precision: {scores['average_precision']:.4f}")
        print(f"  Threshold: {scores['threshold']:.4f}")

    print("\nGenerating test set predictions...")
    test_predictions = generate_test_predictions(
        model,
        test_processed['text'].tolist(),
        test_thresholds,
        os.path.join(CONFIG['results_dir'], 'test_predictions.csv')
    )

    gt_corr, pred_corr = compute_correlation_matrices(test_labels, test_preds, CONFIG['emotion_labels'], CONFIG['results_dir'])

    sample_texts = [
        "إنها على وشك ان تصبح هفت ونص صباحا وأنت وحيد #بؤس 💔",
        "لو بينا ألف زعل لا تشتكين لغيري أنت حتى الدموع اللي بعينك دمعتي",
        "لو بينا ألف زعل لا تشتكين لغيري أنت حتى الدموع اللي بعينك دمعتي",
    ]
    inference_results = infer_emotions(model, sample_texts, test_thresholds, use_mc_dropout=True)
    with open(os.path.join(CONFIG['results_dir'], 'inference_results.json'), 'w', encoding='utf-8') as f:
        json.dump(inference_results, f, ensure_ascii=False, indent=2)
    print("\nInference Results:")
    for result in inference_results:
        print(f"Text: {result['text']}")
        print(f"Emotions: {result['emotions']}")
        print(f"Probabilities: {result['probabilities']}")
        print(f"Uncertainty: {result['uncertainty']}")
        print(f"Attributed Spans: {result['attributed_spans']}")
        logger.info(f"Text: {result['text']}")
        logger.info(f"Emotions: {result['emotions']}")
        logger.info(f"Probabilities: {result['probabilities']}")
        logger.info(f"Uncertainty: {result['uncertainty']}")
        logger.info(f"Attributed Spans: {result['attributed_spans']}")

    plt.figure(figsize=(12, 8))
    plt.subplot(2, 2, 1)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], label='Validation Loss')
    plt.title('Total Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 2)
    plt.plot(history['bce_loss'], label='Train BCE Loss')
    plt.plot(history['val_bce_loss'], label='Validation BCE Loss')
    plt.title('BCE Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 3)
    plt.plot(history['focal_loss'], label='Train Focal Loss')
    plt.plot(history['val_focal_loss'], label='Validation Focal Loss')
    plt.title('Focal Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.subplot(2, 2, 4)
    plt.plot(history['jaccard'], label='Train Jaccard')
    plt.plot(history['val_jaccard'], label='Validation Jaccard')
    plt.title('Jaccard Score')
    plt.xlabel('Epoch')
    plt.ylabel('Jaccard')
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(CONFIG['results_dir'], 'training_history.png'))
    plt.close()



"""# Task
Visualize the workflow of the proposed model from the notebook "/content/final.ipynb" using `graphviz` after the training and evaluation sections, and display the visualization.

## Install necessary library

### Subtask:
Install the `graphviz` library.

**Reasoning**:
The subtask is to install the `graphviz` library. This can be done using pip in a code block.
"""

!pip install graphviz

"""## Define the graph structure

### Subtask:
Create a string representing the workflow of the HiDisc-Emo model as a directed graph using Graphviz DOT syntax.

**Reasoning**:
Create a string variable containing the Graphviz DOT syntax to visualize the model workflow.
"""

dot_graph = """
digraph Proposed_Method_Workflow {
    graph [rankdir=TB, splines=ortho]; // Top to Bottom layout, orthogonal lines
    node [shape=box, style=filled, fillcolor=lightblue]; // Default node style

    // Define Nodes
    "Input Text" [shape=parallelogram, fillcolor=lightgreen];
    "Ground Truth Labels" [shape=parallelogram, fillcolor=lightgreen];
    "Label Embeddings" [shape=parallelogram, fillcolor=lightgreen];

    "Preprocessing" [shape=box];
    "Tokenization & Embedding" [shape=box];
    "MARBERT Encoder" [shape=folder];
    "Token Embeddings" [shape=parallelogram];

    "Span Attention" [shape=box];
    "Span Representation" [shape=box];

    "Graph Construction" [shape=box];
    "Adaptive Graph Module" [shape=box3d];
    "Graph Enhanced Representation" [shape=box];

    "Fusion" [shape=box];
    "Label Transformer" [shape=box3d];
    "Emotion Classifier" [shape=box];
    "Predicted Probabilities" [shape=parallelogram, fillcolor=lightgreen];

    "Loss Calculation" [shape=oval, fillcolor=salmon];
    "Optimizer" [shape=cylinder, fillcolor=yellow];
    "Evaluation Metrics" [shape=oval, fillcolor=salmon];
    "Trained Model" [shape=cylinder, fillcolor=yellow];
    "Inference" [shape=box];
    "Final Emotion Predictions" [shape=parallelogram, fillcolor=lightgreen];
    "Attributed Spans" [shape=parallelogram, fillcolor=lightgreen];

    // Define Edges (Flow)
    "Input Text" -> "Preprocessing";
    "Preprocessing" -> "Tokenization & Embedding";
    "Tokenization & Embedding" -> "MARBERT Encoder";
    "MARBERT Encoder" -> "Token Embeddings";

    "Token Embeddings" -> "Span Attention";
    "Span Attention" -> "Span Representation";

    "Span Representation" -> "Graph Construction";
    "Graph Construction" -> "Adaptive Graph Module";
    "Adaptive Graph Module" -> "Graph Enhanced Representation";

    "Token Embeddings" -> "Fusion";
    "Span Representation" -> "Fusion";
    "Graph Enhanced Representation" -> "Fusion";

    "Fusion" -> "Emotion Classifier";

    "Label Embeddings" -> "Label Transformer";
    "Label Transformer" -> "Emotion Classifier";

    "Emotion Classifier" -> "Predicted Probabilities";

    // Training Flow
    "Predicted Probabilities" -> "Loss Calculation";
    "Ground Truth Labels" -> "Loss Calculation";
    "Label Transformer" -> "Loss Calculation";
    "Loss Calculation" -> "Optimizer";
    "Optimizer" -> "MARBERT Encoder" [xlabel="backprop"];
    "Optimizer" -> "Span Attention" [xlabel="backprop"];
    "Optimizer" -> "Graph Construction" [xlabel="backprop"];
    "Optimizer" -> "Adaptive Graph Module" [xlabel="backprop"];
    "Optimizer" -> "Fusion" [xlabel="backprop"];
    "Optimizer" -> "Emotion Classifier" [xlabel="backprop"];
    "Optimizer" -> "Label Embeddings" [xlabel="backprop"];
    "Optimizer" -> "Label Transformer" [xlabel="backprop"];


    // Evaluation Flow
    "Predicted Probabilities" -> "Evaluation Metrics";
    "Ground Truth Labels" -> "Evaluation Metrics";

    // Inference Flow
    "Trained Model" -> "Inference";
    "Input Text" -> "Inference";
    "Inference" -> "Final Emotion Predictions";
    "Inference" -> "Attributed Spans";

    // Rank alignment for better layout
    { rank=same; "Input Text"; "Ground Truth Labels"; "Label Embeddings" }
    { rank=same; "Preprocessing"; "Label Transformer" }
    { rank=same; "Tokenization & Embedding"; }
    { rank=same; "MARBERT Encoder"; }
    { rank=same; "Token Embeddings"; }
    { rank=same; "Span Attention"; "Graph Construction"; }
    { rank=same; "Span Representation"; "Adaptive Graph Module"; }
    { rank=same; "Graph Enhanced Representation"; }
    { rank=same; "Fusion"; }
    { rank=same; "Emotion Classifier"; }
    { rank=same; "Predicted Probabilities"; }
    { rank=same; "Loss Calculation"; "Evaluation Metrics"; }
    { rank=same; "Optimizer"; "Trained Model"; }
    { rank=same; "Inference"; }
    { rank=same; "Final Emotion Predictions"; "Attributed Spans"; }
}
"""
print(dot_graph)

"""## Render the graph

### Subtask:
Render the graph defined in `dot_graph` using `graphviz`.

**Reasoning**:
Render the graph defined in dot_graph using graphviz.
"""

import graphviz

src = graphviz.Source(dot_graph)
display(src)

"""## Summary:

### Data Analysis Key Findings

*   The workflow of the HiDisc-Emo model was visualized as a directed graph using Graphviz DOT syntax.
*   The visualization includes key components such as "Input Data", "Preprocessing", "MARBERT Encoder", "Span Representation", "Graph Module", "Fusion", "Label Transformer", "Classifier", "Output Predictions", "Loss Calculation", "Evaluation", and "Inference".
*   The graph illustrates the flow of data and processing steps, including connections like "Input Data" to "Preprocessing", "MARBERT Encoder" to "Fusion", "Graph Module" to "Fusion", and "Classifier" to "Output Predictions".
*   Specialized node shapes were used to represent different types of components: boxes for processing steps, a cylinder for the model parameters, ovals for calculation/evaluation/inference stages, parallelograms for data inputs/outputs, and 3D boxes for the "Label Transformer" and "Graph Module".

### Insights or Next Steps

*   The generated graph provides a clear visual overview of the HiDisc-Emo model's architecture and processing pipeline.
*   This visualization can be used for documentation, explanation, and understanding the complex interactions within the model.

"""